/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.equipo.master.persistence.entity;

import co.edu.uniandes.csw.astroDevelopers.usuario.persistence.entity.UsuarioEntity;
import co.edu.uniandes.csw.astroDevelopers.equipo.persistence.entity.EquipoEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(Equipousuario_equipoEntityId.class)
@NamedQueries({
    @NamedQuery(name = "Equipousuario_equipoEntity.getByMasterId", query = "SELECT  u FROM Equipousuario_equipoEntity u WHERE u.equipoId=:equipoId"),
    @NamedQuery(name = "Equipousuario_equipoEntity.deleteEquipousuario_equipoEntity", query = "DELETE FROM Equipousuario_equipoEntity u WHERE u.equipoId=:equipoId and  u.usuario_equipoId=:usuario_equipoId")
})
public class Equipousuario_equipoEntity implements Serializable {

    @Id
    @Column(name = "equipoId")
    private Long equipoId;
    @Id
    @Column(name = "usuario_equipoId")
    private Long usuario_equipoId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "equipoId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity equipoIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "usuario_equipoId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity usuario_equipoIdEntity; 

    public Equipousuario_equipoEntity() {
    }

    public Equipousuario_equipoEntity(Long equipoId, Long usuario_equipoId) {
        this.equipoId =equipoId;
        this.usuario_equipoId = usuario_equipoId;
    }

    public Long getEquipoId() {
        return equipoId;
    }

    public void setEquipoId(Long equipoId) {
        this.equipoId = equipoId;
    }

    public Long getUsuario_equipoId() {
        return usuario_equipoId;
    }

    public void setUsuario_equipoId(Long usuario_equipoId) {
        this.usuario_equipoId = usuario_equipoId;
    }

    public UsuarioEntity getEquipoIdEntity() {
        return equipoIdEntity;
    }

    public void setEquipoIdEntity(UsuarioEntity equipoIdEntity) {
        this.equipoIdEntity = equipoIdEntity;
    }

    public UsuarioEntity getUsuario_equipoIdEntity() {
        return usuario_equipoIdEntity;
    }

    public void setUsuario_equipoIdEntity(UsuarioEntity usuario_equipoIdEntity) {
        this.usuario_equipoIdEntity = usuario_equipoIdEntity;
    }

}
