/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.noticia.master.persistence;
import co.edu.uniandes.csw.astroDevelopers.tag.logic.dto.TagDTO;
import co.edu.uniandes.csw.astroDevelopers.noticia.master.persistence.entity.Noticiatag_noticiaEntity;
import co.edu.uniandes.csw.astroDevelopers.tag.persistence.converter.TagConverter;
import co.edu.uniandes.csw.astroDevelopers.noticia.logic.dto.NoticiaDTO;
import co.edu.uniandes.csw.astroDevelopers.noticia.master.logic.dto.NoticiaMasterDTO;
import co.edu.uniandes.csw.astroDevelopers.noticia.master.persistence.api._INoticiaMasterPersistence;
import co.edu.uniandes.csw.astroDevelopers.noticia.persistence.api.INoticiaPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _NoticiaMasterPersistence implements _INoticiaMasterPersistence {

  	@PersistenceContext(unitName="KanuaUML12PU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected INoticiaPersistence noticiaPersistence;  

    public NoticiaMasterDTO getNoticia(Long noticiaId) {
        NoticiaMasterDTO noticiaMasterDTO = new NoticiaMasterDTO();
        NoticiaDTO noticia = noticiaPersistence.getNoticia(noticiaId);
        noticiaMasterDTO.setNoticiaEntity(noticia);
        noticiaMasterDTO.setListtag_noticia(getNoticiatag_noticiaEntityList(noticiaId));
        return noticiaMasterDTO;
    }

    public Noticiatag_noticiaEntity createNoticiatag_noticiaEntity(Noticiatag_noticiaEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteNoticiatag_noticiaEntity(Long noticiaId, Long tag_noticiaId) {
        Query q = entityManager.createNamedQuery("Noticiatag_noticiaEntity.deleteNoticiatag_noticiaEntity");
        q.setParameter("noticiaId", noticiaId);
        q.setParameter("tag_noticiaId", tag_noticiaId);
        q.executeUpdate();
    }

    public List<TagDTO> getNoticiatag_noticiaEntityList(Long noticiaId) {
        ArrayList<TagDTO> resp = new ArrayList<TagDTO>();
        Query q = entityManager.createNamedQuery("Noticiatag_noticiaEntity.getByMasterId");
        q.setParameter("noticiaId",noticiaId);
        List<Noticiatag_noticiaEntity> qResult =  q.getResultList();
        for (Noticiatag_noticiaEntity entity : qResult) { 
            if(entity.getTag_noticiaIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(TagConverter.entity2PersistenceDTO(entity.getTag_noticiaIdEntity()));
        }
        return resp;
    }

}
