/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410261249

*/

package co.edu.uniandes.csw.astroDevelopers.objetivo.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.astroDevelopers.objetivo.logic.dto.ObjetivoDTO;
import co.edu.uniandes.csw.astroDevelopers.objetivo.persistence.api.IObjetivoPersistence;
import co.edu.uniandes.csw.astroDevelopers.objetivo.persistence.entity.ObjetivoEntity;
import co.edu.uniandes.csw.astroDevelopers.objetivo.persistence.converter.ObjetivoConverter;
import static co.edu.uniandes.csw.astroDevelopers.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ObjetivoPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ObjetivoPersistence.class.getPackage())
				.addPackage(ObjetivoEntity.class.getPackage())
				.addPackage(IObjetivoPersistence.class.getPackage())
                .addPackage(ObjetivoDTO.class.getPackage())
                .addPackage(ObjetivoConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IObjetivoPersistence objetivoPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ObjetivoEntity").executeUpdate();
	}

	private List<ObjetivoEntity> data=new ArrayList<ObjetivoEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ObjetivoEntity entity=new ObjetivoEntity();
			entity.setName(generateRandom(String.class));
			entity.setDescripcion(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createObjetivoTest(){
		ObjetivoDTO dto=new ObjetivoDTO();
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		
		ObjetivoDTO result=objetivoPersistence.createObjetivo(dto);
		
		Assert.assertNotNull(result);
		
		ObjetivoEntity entity=em.find(ObjetivoEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
	}
	
	@Test
	public void getObjetivosTest(){
		List<ObjetivoDTO> list=objetivoPersistence.getObjetivos();
		Assert.assertEquals(list.size(), data.size());
        for(ObjetivoDTO dto:list){
        	boolean found=false;
            for(ObjetivoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getObjetivoTest(){
		ObjetivoEntity entity=data.get(0);
		ObjetivoDTO dto=objetivoPersistence.getObjetivo(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getDescripcion(), dto.getDescripcion());
        
	}
	
	@Test
	public void deleteObjetivoTest(){
		ObjetivoEntity entity=data.get(0);
		objetivoPersistence.deleteObjetivo(entity.getId());
        ObjetivoEntity deleted=em.find(ObjetivoEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateObjetivoTest(){
		ObjetivoEntity entity=data.get(0);
		
		ObjetivoDTO dto=new ObjetivoDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		
		
		objetivoPersistence.updateObjetivo(dto);
		
		
		ObjetivoEntity resp=em.find(ObjetivoEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getDescripcion(), resp.getDescripcion());	
	}
	
	
	
}