/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['model/proyectoModel'], function(proyectoModel) {
    App.Controller._ProyectoController = Backbone.View.extend({
        initialize: function(options) {
            this.modelClass = options.modelClass;
            this.listModelClass = options.listModelClass;
            this.showEdit = true;
            this.showDelete = true;
            this.editTemplate = _.template($('#proyecto').html());
            this.listTemplate = _.template($('#proyectoList').html());
            if (!options || !options.componentId) {
                this.componentId = _.random(0, 100) + "";
            }else{
				this.componentId = options.componentId;
		    }
            var self = this;
            if(self.postInit){
            	self.postInit(options);
            }
        },
        create: function() {
            if (App.Utils.eventExists(this.componentId + '-' +'instead-proyecto-create')) {
                Backbone.trigger(this.componentId + '-' + 'instead-proyecto-create', {view: this});
            } else {
                Backbone.trigger(this.componentId + '-' + 'pre-proyecto-create', {view: this});
                this.currentProyectoModel = new this.modelClass({componentId: this.componentId});
                this._renderEdit();
                Backbone.trigger(this.componentId + '-' + 'post-proyecto-create', {view: this});
            }
        },
        list: function(params) {
            if (params) {
                var data = params.data;
            }
            if (App.Utils.eventExists(this.componentId + '-' +'instead-proyecto-list')) {
                Backbone.trigger(this.componentId + '-' + 'instead-proyecto-list', {view: this, data: data});
            } else {
                Backbone.trigger(this.componentId + '-' + 'pre-proyecto-list', {view: this, data: data});
                var self = this;
				if(!this.proyectoModelList){
                 this.proyectoModelList = new this.listModelClass();
				}
                this.proyectoModelList.fetch({
                    data: data,
                    success: function() {
                        self._renderList();
                        Backbone.trigger(self.componentId + '-' + 'post-proyecto-list', {view: self});
                    },
                    error: function(mode, error) {
                        Backbone.trigger(self.componentId + '-' + 'error', {event: 'proyecto-list', view: self, error: error});
                    }
                });
            }
        },
        edit: function(params) {
            var id = params.id;
            var data = params.data;
            if (App.Utils.eventExists(this.componentId + '-' +'instead-proyecto-edit')) {
                Backbone.trigger(this.componentId + '-' + 'instead-proyecto-edit', {view: this, id: id, data: data});
            } else {
                Backbone.trigger(this.componentId + '-' + 'pre-proyecto-edit', {view: this, id: id, data: data});
                if (this.proyectoModelList) {
                    this.currentProyectoModel = this.proyectoModelList.get(id);
                    this.currentProyectoModel.set('componentId',this.componentId); 
                    this._renderEdit();
                    Backbone.trigger(this.componentId + '-' + 'post-proyecto-edit', {view: this, id: id, data: data});
                } else {
                    var self = this;
                    this.currentProyectoModel = new this.modelClass({id: id});
                    this.currentProyectoModel.fetch({
                        data: data,
                        success: function() {
                            self.currentProyectoModel.set('componentId',self.componentId); 
                            self._renderEdit();
                            Backbone.trigger(self.componentId + '-' + 'post-proyecto-edit', {view: this, id: id, data: data});
                        },
                        error: function() {
                            Backbone.trigger(self.componentId + '-' + 'error', {event: 'proyecto-edit', view: self, id: id, data: data, error: error});
                        }
                    });
                }
            }
        },
        destroy: function(params) {
            var id = params.id;
            var self = this;
            if (App.Utils.eventExists(this.componentId + '-' +'instead-proyecto-delete')) {
                Backbone.trigger(this.componentId + '-' + 'instead-proyecto-delete', {view: this, id: id});
            } else {
                Backbone.trigger(this.componentId + '-' + 'pre-proyecto-delete', {view: this, id: id});
                var deleteModel;
                if (this.proyectoModelList) {
                    deleteModel = this.proyectoModelList.get(id);
                } else {
                    deleteModel = new this.modelClass({id: id});
                }
                deleteModel.destroy({
                    success: function() {
                        Backbone.trigger(self.componentId + '-' + 'post-proyecto-delete', {view: self, model: deleteModel});
                    },
                    error: function() {
                        Backbone.trigger(self.componentId + '-' + 'error', {event: 'proyecto-delete', view: self, error: error});
                    }
                });
            }
        },
		_loadRequiredComponentsData: function(callBack) {
            var self = this;
            var listReady = _.after(1, function(){
                callBack();
            }); 
            var listDataReady = function(componentName, model, aliasModel){
            if(aliasModel){
                self[aliasModel] = model;
            } else {
            	self[componentName] = model;
            }    
                listReady();
            };
				App.Utils.getComponentList('equipoComponent',listDataReady,'equipo_proyectoComponent');
        },
        save: function() {
            var self = this;
            var model = $('#' + this.componentId + '-proyectoForm').serializeObject();
            if (App.Utils.eventExists(this.componentId + '-' +'instead-proyecto-save')) {
                Backbone.trigger(this.componentId + '-' + 'instead-proyecto-save', {view: this, model : model});
            } else {
                Backbone.trigger(this.componentId + '-' + 'pre-proyecto-save', {view: this, model : model});
                this.currentProyectoModel.set(model);
                this.currentProyectoModel.save({},
                        {
                            success: function(model) {
                                Backbone.trigger(self.componentId + '-' + 'post-proyecto-save', {model: self.currentProyectoModel});
                            },
                            error: function(error) {
                                Backbone.trigger(self.componentId + '-' + 'error', {event: 'proyecto-save', view: self, error: error});
                            }
                        });
            }
        },
        _renderList: function() {
            var self = this;
            this.$el.slideUp("fast", function() {
                self.$el.html(self.listTemplate({proyectos: self.proyectoModelList.models, componentId: self.componentId, showEdit : self.showEdit , showDelete : self.showDelete}));
                self.$el.slideDown("fast");
            });
        },
        _renderEdit: function() {
            var self = this;
            this.$el.slideUp("fast", function() {
                self.$el.html(self.editTemplate({proyecto: self.currentProyectoModel, componentId: self.componentId , showEdit : self.showEdit , showDelete : self.showDelete
 
				    ,equipo_proyecto: self.equipo_proyectoComponent
 
				}));
                self.$el.slideDown("fast");
            });
        }
    });
    return App.Controller._ProyectoController;
});