/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['controller/_noticiaController','delegate/noticiaDelegate'], function() {
    App.Controller.NoticiaController = App.Controller._NoticiaController.extend({
        postInit: function(options)
        {
            var self= this;
            this.mostrarInfoNoticiaTemplate=_.template($('#mostrar-noticia').html());
        },
        _renderMostrarInfoNoticia: function (params)
        {
            var self = this;
            this.$el.slideUp("fast", function() {
                /*Establece que en el <div> se despliegue el template de la variable ��. Como par�metros entran las variables establecidas dentro de los tags <%%> con sus valores como un objeto JSON. En este caso, la propiedad sports tendr� la lista que instanci� �sportSearch� en la variable del bucle <% _.each(sports, function(sport) { %>*/
 
                self.$el.html(self.mostrarInfoNoticiaTemplate({noticia: self.currentNoticiaModel, componentId: self.componentId}));
                self.$el.slideDown("fast");
                //Backbone.trigger(self.componentId + '-' + 'post-mostrar-noticia', {equipoId: equipoId});  
            });
        },
        mostrarInfoNoticia: function(params)
        {
            var id = params.id;
            var data = params.data;
            if(this.noticiaModelList)
            {
                this.currentNoticiaModel = this.noticiaModelList.get(id);
                this.currentNoticiaModel.set('componentId',this.componentId);
                this._renderMostrarInfoNoticia(params);
            }
            else
            {
                var self = this;
                this.currentNoticiaModel = new this.modelClass({id: id});
                this.currentNoticiaModel.fetch({
                    data : data,
                    success: function(){
                        self.currentNoticiaModel.set('componentId',self.componentId);
                        self._renderMostrarInfoNoticia(params);
                    },
                    error: function(){
                        Backbone.trigger(self.componentId + '-' + 'error', {event: 'mostrar-noticia', view: self, id: id, data: data, error: error});
                    }
                });       
            }
        }
    });
    return App.Controller.NoticiaController;
}); 