/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['controller/_proyectoController','delegate/proyectoDelegate'], function() {
    App.Controller.ProyectoController = App.Controller._ProyectoController.extend({
        //Se tiene que poner el posInit y declarar la plantilla
        postInit: function(options) {
            var self = this;
            this.mostrarInfoProyectoTemplate = _.template($('#proyecto-mostrar-info').html());
            this.generarContactoTemplate = _.template($('#generar-contacto').html());
            this.realizarSolicitudTemplate = _.template($('#realizar-solicitud').html());
        },
        //se define este metodo que es el que quita lo viejo y pone lo nuevo. Le manda la informacion a la plantilla
        _renderMostrarInfoProyecto: function(params) {
            var self = this;
            var equipoId = params.equipoId;
            /*Aqu� se utiliza el efecto gr�fico backbone deslizar. �$el� hace referencia al <div id=�main�> ubicado en el index.html. Dentro de este div se despliegue la tabla.*/
            this.$el.slideUp("fast", function() {
                /*Establece que en el <div> se despliegue el template de la variable ��. Como par�metros entran las variables establecidas dentro de los tags <%%> con sus valores como un objeto JSON. En este caso, la propiedad sports tendr� la lista que instanci� �sportSearch� en la variable del bucle <% _.each(sports, function(sport) { %>*/
 
                self.$el.html(self.mostrarInfoProyectoTemplate({proyecto: self.currentProyectoModel, componentId: self.componentId, equipos: self.equipo_proyectoComponent}));
                self.$el.slideDown("fast");
                Backbone.trigger(self.componentId + '-' + 'post-proyecto-mostrar-info', {equipoId: equipoId});
                
            });
        },
        //esto es el metodo que obtiene la informacion del proyecto que se necesita actualmente para mostrar su informacion.
        mostrarInfoProyecto: function(params) {
            var id = params.id;
            var data = params.data;
            if (this.proyectoModelList) {
                this.currentProyectoModel = this.proyectoModelList.get(id);
                this.currentProyectoModel.set('componentId',this.componentId); 
                this._renderMostrarInfoProyecto(params);
            }
            else {
                var self = this;
                this.currentProyectoModel = new this.modelClass({id: id});
                this.currentProyectoModel.fetch({
                    data: data,
                    success: function() {
                        self.currentProyectoModel.set('componentId',self.componentId); 
                        self._renderMostrarInfoProyecto(params);
                    },
                    error: function() {
                        Backbone.trigger(self.componentId + '-' + 'error', {event: 'proyecto-mostrar-info', view: self, id: id, data: data, error: error});
                    }
                });
            }
        },
        
        _renderGenerarContacto: function(params) {
            var self = this;
            var equipoId = params.equipoId;
            /*Aqu� se utiliza el efecto gr�fico backbone deslizar. �$el� hace referencia al <div id=�main�> ubicado en el index.html. Dentro de este div se despliegue la tabla.*/
            this.$el.slideUp("fast", function() {
                /*Establece que en el <div> se despliegue el template de la variable ��. Como par�metros entran las variables establecidas dentro de los tags <%%> con sus valores como un objeto JSON. En este caso, la propiedad sports tendr� la lista que instanci� �sportSearch� en la variable del bucle <% _.each(sports, function(sport) { %>*/
 
                self.$el.html(self.generarContactoTemplate({proyecto: self.currentProyectoModel, componentId: self.componentId, equipos: self.equipo_proyectoComponent}));
                self.$el.slideDown("fast");
                Backbone.trigger(self.componentId + '-' + '-generar-contacto', {equipoId: equipoId});
                
            });
            
        },        
        
        generarContacto: function(params) {
            var id = params.id;
            var data = params.data;
            
            if (this.proyectoModelList) {
                this.currentProyectoModel = this.proyectoModelList.get(id);
                this.currentProyectoModel.set('componentId',this.componentId); 
                this._renderGenerarContacto(params);
            }
        },
        
        _renderRealizarSolicitud: function(params) {
           
           var self = this;
           var equipoId = params.equipoId;
           this.$el.slideUp("fast", function() {
                self.$el.html(self.realizarSolicitudTemplate({proyecto: self.currentProyectoModel, componentId: self.componentId, equipos: self.equipo_proyectoComponent}));
                self.$el.slideDown("fast");
                Backbone.trigger(self.componentId + '-' + '-inscribirse', {equipoId: equipoId});
                
            });          
            
        },
        
        realizarSolicitud: function(params) {
            var id = params.id;
            var data = params.data;
            
            if (this.proyectoModelList) {
                this.currentProyectoModel = this.proyectoModelList.get(id);
                this.currentProyectoModel.set('componentId',this.componentId); 
                this._renderRealizarSolicitud(params);
            }
        },
    });
    return App.Controller.ProyectoController;
}); 