/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.objetivo.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.astroDevelopers.objetivo.logic.dto.ObjetivoDTO;
import co.edu.uniandes.csw.astroDevelopers.objetivo.logic.api._IObjetivoLogicService;

public abstract class _ObjetivoMockLogicService implements _IObjetivoLogicService {

	private Long id= new Long(1);
	protected List<ObjetivoDTO> data=new ArrayList<ObjetivoDTO>();

	public ObjetivoDTO createObjetivo(ObjetivoDTO objetivo){
		id++;
		objetivo.setId(id);
		data.add(objetivo);
		return objetivo;
    }

	public List<ObjetivoDTO> getObjetivos(){
		return data; 
	}

	public ObjetivoDTO getObjetivo(Long id){
		for(ObjetivoDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteObjetivo(Long id){
	    ObjetivoDTO delete=null;
		for(ObjetivoDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateObjetivo(ObjetivoDTO objetivo){
	    ObjetivoDTO delete=null;
		for(ObjetivoDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(objetivo);
		} 
	}	
}