/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.charla.master.persistence;
import co.edu.uniandes.csw.astroDevelopers.tag.logic.dto.TagDTO;
import co.edu.uniandes.csw.astroDevelopers.charla.master.persistence.entity.Charlatag_charlaEntity;
import co.edu.uniandes.csw.astroDevelopers.tag.persistence.converter.TagConverter;
import co.edu.uniandes.csw.astroDevelopers.charla.logic.dto.CharlaDTO;
import co.edu.uniandes.csw.astroDevelopers.charla.master.logic.dto.CharlaMasterDTO;
import co.edu.uniandes.csw.astroDevelopers.charla.master.persistence.api._ICharlaMasterPersistence;
import co.edu.uniandes.csw.astroDevelopers.charla.persistence.api.ICharlaPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _CharlaMasterPersistence implements _ICharlaMasterPersistence {

  	@PersistenceContext(unitName="KanuaUML12PU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected ICharlaPersistence charlaPersistence;  

    public CharlaMasterDTO getCharla(Long charlaId) {
        CharlaMasterDTO charlaMasterDTO = new CharlaMasterDTO();
        CharlaDTO charla = charlaPersistence.getCharla(charlaId);
        charlaMasterDTO.setCharlaEntity(charla);
        charlaMasterDTO.setListtag_charla(getCharlatag_charlaEntityList(charlaId));
        return charlaMasterDTO;
    }

    public Charlatag_charlaEntity createCharlatag_charlaEntity(Charlatag_charlaEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteCharlatag_charlaEntity(Long charlaId, Long tag_charlaId) {
        Query q = entityManager.createNamedQuery("Charlatag_charlaEntity.deleteCharlatag_charlaEntity");
        q.setParameter("charlaId", charlaId);
        q.setParameter("tag_charlaId", tag_charlaId);
        q.executeUpdate();
    }

    public List<TagDTO> getCharlatag_charlaEntityList(Long charlaId) {
        ArrayList<TagDTO> resp = new ArrayList<TagDTO>();
        Query q = entityManager.createNamedQuery("Charlatag_charlaEntity.getByMasterId");
        q.setParameter("charlaId",charlaId);
        List<Charlatag_charlaEntity> qResult =  q.getResultList();
        for (Charlatag_charlaEntity entity : qResult) { 
            if(entity.getTag_charlaIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(TagConverter.entity2PersistenceDTO(entity.getTag_charlaIdEntity()));
        }
        return resp;
    }

}
