/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.charla.master.logic.dto;

import co.edu.uniandes.csw.astroDevelopers.tag.logic.dto.TagDTO;
import co.edu.uniandes.csw.astroDevelopers.charla.logic.dto.CharlaDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _CharlaMasterDTO {

 
    protected CharlaDTO charlaEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public CharlaDTO getCharlaEntity() {
        return charlaEntity;
    }

    public void setCharlaEntity(CharlaDTO charlaEntity) {
        this.charlaEntity = charlaEntity;
    }
    
    public List<TagDTO> createtag_charla;
    public List<TagDTO> updatetag_charla;
    public List<TagDTO> deletetag_charla;
    public List<TagDTO> listtag_charla;	
	
	
	
    public List<TagDTO> getCreatetag_charla(){ return createtag_charla; };
    public void setCreatetag_charla(List<TagDTO> createtag_charla){ this.createtag_charla=createtag_charla; };
    public List<TagDTO> getUpdatetag_charla(){ return updatetag_charla; };
    public void setUpdatetag_charla(List<TagDTO> updatetag_charla){ this.updatetag_charla=updatetag_charla; };
    public List<TagDTO> getDeletetag_charla(){ return deletetag_charla; };
    public void setDeletetag_charla(List<TagDTO> deletetag_charla){ this.deletetag_charla=deletetag_charla; };
    public List<TagDTO> getListtag_charla(){ return listtag_charla; };
    public void setListtag_charla(List<TagDTO> listtag_charla){ this.listtag_charla=listtag_charla; };	
	
	
}

