/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.taller.master.logic.dto;

import co.edu.uniandes.csw.astroDevelopers.tag.logic.dto.TagDTO;
import co.edu.uniandes.csw.astroDevelopers.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.astroDevelopers.taller.logic.dto.TallerDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _TallerMasterDTO {

 
    protected TallerDTO tallerEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public TallerDTO getTallerEntity() {
        return tallerEntity;
    }

    public void setTallerEntity(TallerDTO tallerEntity) {
        this.tallerEntity = tallerEntity;
    }
    
    public List<TagDTO> createtag_taller;
    public List<TagDTO> updatetag_taller;
    public List<TagDTO> deletetag_taller;
    public List<TagDTO> listtag_taller;	
    public List<UsuarioDTO> createusuario;
    public List<UsuarioDTO> updateusuario;
    public List<UsuarioDTO> deleteusuario;
    public List<UsuarioDTO> listusuario;	
	
	
	
    public List<TagDTO> getCreatetag_taller(){ return createtag_taller; };
    public void setCreatetag_taller(List<TagDTO> createtag_taller){ this.createtag_taller=createtag_taller; };
    public List<TagDTO> getUpdatetag_taller(){ return updatetag_taller; };
    public void setUpdatetag_taller(List<TagDTO> updatetag_taller){ this.updatetag_taller=updatetag_taller; };
    public List<TagDTO> getDeletetag_taller(){ return deletetag_taller; };
    public void setDeletetag_taller(List<TagDTO> deletetag_taller){ this.deletetag_taller=deletetag_taller; };
    public List<TagDTO> getListtag_taller(){ return listtag_taller; };
    public void setListtag_taller(List<TagDTO> listtag_taller){ this.listtag_taller=listtag_taller; };	
    public List<UsuarioDTO> getCreateusuario(){ return createusuario; };
    public void setCreateusuario(List<UsuarioDTO> createusuario){ this.createusuario=createusuario; };
    public List<UsuarioDTO> getUpdateusuario(){ return updateusuario; };
    public void setUpdateusuario(List<UsuarioDTO> updateusuario){ this.updateusuario=updateusuario; };
    public List<UsuarioDTO> getDeleteusuario(){ return deleteusuario; };
    public void setDeleteusuario(List<UsuarioDTO> deleteusuario){ this.deleteusuario=deleteusuario; };
    public List<UsuarioDTO> getListusuario(){ return listusuario; };
    public void setListusuario(List<UsuarioDTO> listusuario){ this.listusuario=listusuario; };	
	
	
}

