/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.taller.master.logic.ejb;

import co.edu.uniandes.csw.astroDevelopers.tag.logic.dto.TagDTO;
import co.edu.uniandes.csw.astroDevelopers.tag.persistence.api.ITagPersistence;
import co.edu.uniandes.csw.astroDevelopers.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.astroDevelopers.usuario.persistence.api.IUsuarioPersistence;
import co.edu.uniandes.csw.astroDevelopers.taller.logic.dto.TallerDTO;
import co.edu.uniandes.csw.astroDevelopers.taller.master.logic.api._ITallerMasterLogicService;
import co.edu.uniandes.csw.astroDevelopers.taller.master.logic.dto.TallerMasterDTO;
import co.edu.uniandes.csw.astroDevelopers.taller.master.persistence.api.ITallerMasterPersistence;
import co.edu.uniandes.csw.astroDevelopers.taller.master.persistence.entity.Tallertag_tallerEntity;
import co.edu.uniandes.csw.astroDevelopers.taller.master.persistence.entity.TallerusuarioEntity;
import co.edu.uniandes.csw.astroDevelopers.taller.persistence.api.ITallerPersistence;
import javax.inject.Inject;

public abstract class _TallerMasterLogicService implements _ITallerMasterLogicService {

    @Inject
    protected ITallerPersistence tallerPersistance;
    @Inject
    protected ITallerMasterPersistence tallerMasterPersistance;
    @Inject
    protected IUsuarioPersistence usuarioPersistance;
    @Inject
    protected ITagPersistence tagPersistance;

    public TallerMasterDTO createMasterTaller(TallerMasterDTO taller) {
        TallerDTO persistedTallerDTO = tallerPersistance.createTaller(taller.getTallerEntity());
        if (taller.getCreatetag_taller() != null) {
            for (TagDTO tagDTO : taller.getCreatetag_taller()) {
                TagDTO createdTagDTO = tagPersistance.createTag(tagDTO);
                Tallertag_tallerEntity tallerTagEntity = new Tallertag_tallerEntity(persistedTallerDTO.getId(), createdTagDTO.getId());
                tallerMasterPersistance.createTallertag_tallerEntity(tallerTagEntity);
            }
        }
        if (taller.getCreateusuario() != null) {
            for (UsuarioDTO usuarioDTO : taller.getCreateusuario()) {
                UsuarioDTO createdUsuarioDTO = usuarioPersistance.createUsuario(usuarioDTO);
                TallerusuarioEntity tallerUsuarioEntity = new TallerusuarioEntity(persistedTallerDTO.getId(), createdUsuarioDTO.getId());
                tallerMasterPersistance.createTallerusuarioEntity(tallerUsuarioEntity);
            }
        }
        // update tag
        if (taller.getUpdatetag_taller() != null) {
            for (TagDTO tagDTO : taller.getUpdatetag_taller()) {
                tagPersistance.updateTag(tagDTO);
                Tallertag_tallerEntity tallerTagEntity = new Tallertag_tallerEntity(persistedTallerDTO.getId(), tagDTO.getId());
                tallerMasterPersistance.createTallertag_tallerEntity(tallerTagEntity);
            }
        }
        // update usuario
        if (taller.getUpdateusuario() != null) {
            for (UsuarioDTO usuarioDTO : taller.getUpdateusuario()) {
                usuarioPersistance.updateUsuario(usuarioDTO);
                TallerusuarioEntity tallerUsuarioEntity = new TallerusuarioEntity(persistedTallerDTO.getId(), usuarioDTO.getId());
                tallerMasterPersistance.createTallerusuarioEntity(tallerUsuarioEntity);
            }
        }
        return taller;
    }

    public TallerMasterDTO getMasterTaller(Long id) {
        return tallerMasterPersistance.getTaller(id);
    }

    public void deleteMasterTaller(Long id) {
        tallerPersistance.deleteTaller(id);
    }

    public void updateMasterTaller(TallerMasterDTO taller) {
        tallerPersistance.updateTaller(taller.getTallerEntity());

        //---- FOR RELATIONSHIP
        // persist new tag
        if (taller.getCreatetag_taller() != null) {
            for (TagDTO tagDTO : taller.getCreatetag_taller()) {
                TagDTO createdTagDTO = tagPersistance.createTag(tagDTO);
                Tallertag_tallerEntity tallerTagEntity = new Tallertag_tallerEntity(taller.getTallerEntity().getId(), createdTagDTO.getId());
                tallerMasterPersistance.createTallertag_tallerEntity(tallerTagEntity);
            }
        }
        // update tag
        if (taller.getUpdatetag_taller() != null) {
            for (TagDTO tagDTO : taller.getUpdatetag_taller()) {
                tagPersistance.updateTag(tagDTO);
            }
        }
        // delete tag
        if (taller.getDeletetag_taller() != null) {
            for (TagDTO tagDTO : taller.getDeletetag_taller()) {
                tallerMasterPersistance.deleteTallertag_tallerEntity(taller.getTallerEntity().getId(), tagDTO.getId());
                tagPersistance.deleteTag(tagDTO.getId());
            }
        }
        // delete usuario
        if (taller.getDeleteusuario() != null) {
            for (UsuarioDTO usuarioDTO : taller.getDeleteusuario()) {
                tallerMasterPersistance.deleteTallerusuarioEntity(taller.getTallerEntity().getId(), usuarioDTO.getId());
            }
        }
        // persist new usuario
        if (taller.getCreateusuario() != null) {
            for (UsuarioDTO usuarioDTO : taller.getCreateusuario()) {
                TallerusuarioEntity tallerUsuarioEntity = new TallerusuarioEntity(taller.getTallerEntity().getId(), usuarioDTO.getId());
                tallerMasterPersistance.createTallerusuarioEntity(tallerUsuarioEntity);
            }
        }
        // update usuario
        if (taller.getUpdateusuario() != null) {
            for (UsuarioDTO usuarioDTO : taller.getUpdateusuario()) {
                tallerMasterPersistance.deleteTallerusuarioEntity(taller.getTallerEntity().getId(), usuarioDTO.getId());
                usuarioPersistance.updateUsuario(usuarioDTO);
                TallerusuarioEntity tallerUsuarioEntity = new TallerusuarioEntity(taller.getId(), usuarioDTO.getId());
                tallerMasterPersistance.createTallerusuarioEntity(tallerUsuarioEntity);
                
            }
        }
    }
}
