/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.taller.master.persistence;

import co.edu.uniandes.csw.astroDevelopers.taller.logic.dto.TallerDTO;
import co.edu.uniandes.csw.astroDevelopers.taller.master.persistence.api.ITallerMasterPersistence;
import co.edu.uniandes.csw.astroDevelopers.taller.persistence.converter.TallerConverter;
import co.edu.uniandes.csw.astroDevelopers.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.astroDevelopers.usuario.persistence.UsuarioPersistence;
import java.util.List;
import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;
import javax.persistence.Query;

@Default
@Stateless 
@LocalBean
public class TallerMasterPersistence extends _TallerMasterPersistence  implements ITallerMasterPersistence {
    
    public String buscarTallersPorTag(String tag) {
        // https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/5/html/RESTEasy_Reference_Guide/Using__Path_and__GET___POST__etc..html
        // Query q = entityManager.createQuery("select u from ProyectoEntity u inner join Proyectotag_proyectoEntity s on s.proyectoId=u.id inner join TagEntity t on t.id=s.tag_proyectoId where t.name=:valortag");
        // q.setParameter("valortag",tag);
        String tags[]=tag.split("\\;");
        String condicion="";
        for (int i=0; i<tags.length; i++)
        {
            if (!condicion.isEmpty())
            {
                condicion+=" OR ";
            }
            condicion+="t.name=:valortag"+i;
        }
        Query q=null;
        if (tag.isEmpty())
        {
            q = entityManager.createQuery("select u from TallerEntity u");
        }
        else
        {
            q = entityManager.createQuery("select u from TallerEntity u inner join Tallertag_tallerEntity s on s.tallerId=u.id inner join TagEntity t on t.id=s.tag_tallerId where "+condicion);
            for(int j=0; j<tags.length; j++)
            {
                q.setParameter("valortag"+j,tags[j]);
            }
        }
        List<TallerDTO> tallers=TallerConverter.entity2PersistenceDTOList(q.getResultList());
        String ids="";
        for(TallerDTO taller:tallers)
        {
            if(!ids.isEmpty())
            {
                ids+=",";
            }
            ids+=taller.getId();
        }
        return ids;
    }
    
    public String inscribirTaller(String email) {
        /*
        Ver que usuario tiene ese email!!!
        Ver el ID del usuario!!
        Insertar a la tabla        
        */
        
        //Query q = entityManager.createQuery("select u from TallerEntity u inner join TallerusuarioEntity s on s.tallerId=u.id");
        /*
        Query q = entityManager.createQuery("select u from TallerusuarioEntity u");
        q.setParameter("email", "%"+email+"%");
        List<TallerDTO> talleres = TallerConverter.entity2PersistenceDTOList(q.getResultList());
        if(talleres.size() != 0) {
            return "Ya se encuentra inscrito";
        }
                */
        
        String ans = "";
        
        UsuarioDTO results = (UsuarioDTO) entityManager.createQuery("SELECT t FROM UsuarioEntity t where t.email = :value1")
                        .setParameter("value1", email).getSingleResult();
        return results.toString();
    }

}