/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.equipo.master.persistence.api;

import co.edu.uniandes.csw.astroDevelopers.equipo.master.persistence.entity.Equiposolicitud_proyectoEntity;
import co.edu.uniandes.csw.astroDevelopers.solicitud.logic.dto.SolicitudDTO;
import co.edu.uniandes.csw.astroDevelopers.equipo.master.persistence.entity.Equipousuario_equipoEntity;
import co.edu.uniandes.csw.astroDevelopers.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.astroDevelopers.equipo.master.logic.dto.EquipoMasterDTO;
import java.util.List;

public interface _IEquipoMasterPersistence {

	public EquipoMasterDTO getEquipo(Long equipoId);
	
	
    public Equiposolicitud_proyectoEntity createEquiposolicitud_proyectoEntity(Equiposolicitud_proyectoEntity entity);
    public void deleteEquiposolicitud_proyectoEntity(Long equipoId, Long solicitud_proyectoId);
    public List<SolicitudDTO> getEquiposolicitud_proyectoEntityList(Long equipoId);
    public Equipousuario_equipoEntity createEquipousuario_equipoEntity(Equipousuario_equipoEntity entity);
    public void deleteEquipousuario_equipoEntity(Long equipoId, Long usuario_equipoId);
    public List<UsuarioDTO> getEquipousuario_equipoEntityList(Long equipoId);
   
  
}
