/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.proyecto.master.persistence.entity;

import co.edu.uniandes.csw.astroDevelopers.objetivo.persistence.entity.ObjetivoEntity;
import co.edu.uniandes.csw.astroDevelopers.proyecto.persistence.entity.ProyectoEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(Proyectoobjetivo_proyectoEntityId.class)
@NamedQueries({
    @NamedQuery(name = "Proyectoobjetivo_proyectoEntity.getByMasterId", query = "SELECT  u FROM Proyectoobjetivo_proyectoEntity u WHERE u.proyectoId=:proyectoId"),
    @NamedQuery(name = "Proyectoobjetivo_proyectoEntity.deleteProyectoobjetivo_proyectoEntity", query = "DELETE FROM Proyectoobjetivo_proyectoEntity u WHERE u.proyectoId=:proyectoId and  u.objetivo_proyectoId=:objetivo_proyectoId")
})
public class Proyectoobjetivo_proyectoEntity implements Serializable {

    @Id
    @Column(name = "proyectoId")
    private Long proyectoId;
    @Id
    @Column(name = "objetivo_proyectoId")
    private Long objetivo_proyectoId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "proyectoId", referencedColumnName = "id")
    @JoinFetch
    private ObjetivoEntity proyectoIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "objetivo_proyectoId", referencedColumnName = "id")
    @JoinFetch
    private ObjetivoEntity objetivo_proyectoIdEntity; 

    public Proyectoobjetivo_proyectoEntity() {
    }

    public Proyectoobjetivo_proyectoEntity(Long proyectoId, Long objetivo_proyectoId) {
        this.proyectoId =proyectoId;
        this.objetivo_proyectoId = objetivo_proyectoId;
    }

    public Long getProyectoId() {
        return proyectoId;
    }

    public void setProyectoId(Long proyectoId) {
        this.proyectoId = proyectoId;
    }

    public Long getObjetivo_proyectoId() {
        return objetivo_proyectoId;
    }

    public void setObjetivo_proyectoId(Long objetivo_proyectoId) {
        this.objetivo_proyectoId = objetivo_proyectoId;
    }

    public ObjetivoEntity getProyectoIdEntity() {
        return proyectoIdEntity;
    }

    public void setProyectoIdEntity(ObjetivoEntity proyectoIdEntity) {
        this.proyectoIdEntity = proyectoIdEntity;
    }

    public ObjetivoEntity getObjetivo_proyectoIdEntity() {
        return objetivo_proyectoIdEntity;
    }

    public void setObjetivo_proyectoIdEntity(ObjetivoEntity objetivo_proyectoIdEntity) {
        this.objetivo_proyectoIdEntity = objetivo_proyectoIdEntity;
    }

}
