/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.rol.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.astroDevelopers.rol.logic.dto.RolDTO;
import co.edu.uniandes.csw.astroDevelopers.rol.persistence.api._IRolPersistence;
import co.edu.uniandes.csw.astroDevelopers.rol.persistence.converter.RolConverter;
import co.edu.uniandes.csw.astroDevelopers.rol.persistence.entity.RolEntity;

public abstract class _RolPersistence implements _IRolPersistence {

  	@PersistenceContext(unitName="KanuaUML12PU")
 
	protected EntityManager entityManager;
	
	public RolDTO createRol(RolDTO rol) {
		RolEntity entity=RolConverter.persistenceDTO2Entity(rol);
		entityManager.persist(entity);
		return RolConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<RolDTO> getRols() {
		Query q = entityManager.createQuery("select u from RolEntity u");
		return RolConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public RolDTO getRol(Long id) {
		return RolConverter.entity2PersistenceDTO(entityManager.find(RolEntity.class, id));
	}

	public void deleteRol(Long id) {
		RolEntity entity=entityManager.find(RolEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateRol(RolDTO detail) {
		RolEntity entity=entityManager.merge(RolConverter.persistenceDTO2Entity(detail));
		RolConverter.entity2PersistenceDTO(entity);
	}

}