/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.equipo.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.astroDevelopers.equipo.logic.dto.EquipoDTO;
import co.edu.uniandes.csw.astroDevelopers.equipo.logic.api.IEquipoLogicService;
import co.edu.uniandes.csw.astroDevelopers.equipo.master.logic.api._IEquipoMasterLogicService;
import co.edu.uniandes.csw.astroDevelopers.equipo.master.logic.dto.EquipoMasterDTO;
import co.edu.uniandes.csw.astroDevelopers.usuario.logic.api.IUsuarioLogicService;
import co.edu.uniandes.csw.astroDevelopers.solicitud.logic.api.ISolicitudLogicService;
import co.edu.uniandes.csw.astroDevelopers.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.astroDevelopers.solicitud.logic.dto.SolicitudDTO;
import javax.inject.Inject;


public abstract class _EquipoMasterMockLogicService implements _IEquipoMasterLogicService {

    protected static ArrayList<EquipoMasterDTO> equipoMasterDtosList = new ArrayList<EquipoMasterDTO>() ;
    @Inject
    protected IUsuarioLogicService usuarioPersistance;
    @Inject
    protected ISolicitudLogicService solicitudPersistance;
    @Inject
    protected IEquipoLogicService equipoPersistance;

    public EquipoMasterDTO createMasterEquipo(EquipoMasterDTO equipo) {

        equipoPersistance.createEquipo(equipo.getEquipoEntity());
        for (SolicitudDTO dto : equipo.getCreatesolicitud_proyecto()) {
            solicitudPersistance.createSolicitud(dto);
        }
        for (UsuarioDTO dto : equipo.getCreateusuario_equipo()) {
            usuarioPersistance.createUsuario(dto);
        }
        equipoMasterDtosList.add(equipo);
        return equipo;
    }

    public EquipoMasterDTO getMasterEquipo(Long id) {
        for (EquipoMasterDTO equipoMasterDTO : equipoMasterDtosList) {
            if (equipoMasterDTO.getEquipoEntity().getId() == id) {
                return equipoMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterEquipo(Long id) {
        for (EquipoMasterDTO equipoMasterDTO : equipoMasterDtosList) {
            if (equipoMasterDTO.getEquipoEntity().getId() == id) {

                for (SolicitudDTO dto : equipoMasterDTO.getCreatesolicitud_proyecto()) {
                    solicitudPersistance.deleteSolicitud(dto.getId());
                }
                equipoPersistance.deleteEquipo(equipoMasterDTO.getId());
                equipoMasterDtosList.remove(equipoMasterDTO);
                for (UsuarioDTO dto : equipoMasterDTO.getCreateusuario_equipo()) {
                    usuarioPersistance.deleteUsuario(dto.getId());
                }
                equipoPersistance.deleteEquipo(equipoMasterDTO.getId());
                equipoMasterDtosList.remove(equipoMasterDTO);
            }
        }

    }

    public void updateMasterEquipo(EquipoMasterDTO equipo) {

        // update Solicitud
        if (equipo.getUpdatesolicitud_proyecto() != null) {
            for (SolicitudDTO dto : equipo.getUpdatesolicitud_proyecto()) {
                solicitudPersistance.updateSolicitud(dto);
            }
        }
        // persist new Solicitud
        if (equipo.getCreatesolicitud_proyecto() != null) {
            for (SolicitudDTO dto : equipo.getCreatesolicitud_proyecto()) {
                SolicitudDTO persistedSolicitudDTO = solicitudPersistance.createSolicitud(dto);
                dto = persistedSolicitudDTO;
            }
        }
        // delete Solicitud
        if (equipo.getDeletesolicitud_proyecto() != null) {
            for (SolicitudDTO dto : equipo.getDeletesolicitud_proyecto()) {

                solicitudPersistance.deleteSolicitud(dto.getId());
            }
        }
        // update Usuario
        if (equipo.getUpdateusuario_equipo() != null) {
            for (UsuarioDTO dto : equipo.getUpdateusuario_equipo()) {
                usuarioPersistance.updateUsuario(dto);
            }
        }
        // persist new Usuario
        if (equipo.getCreateusuario_equipo() != null) {
            for (UsuarioDTO dto : equipo.getCreateusuario_equipo()) {
                UsuarioDTO persistedUsuarioDTO = usuarioPersistance.createUsuario(dto);
                dto = persistedUsuarioDTO;
            }
        }
        // delete Usuario
        if (equipo.getDeleteusuario_equipo() != null) {
            for (UsuarioDTO dto : equipo.getDeleteusuario_equipo()) {

                usuarioPersistance.deleteUsuario(dto.getId());
            }
        }
    }
}