/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410261249

*/

package co.edu.uniandes.csw.astroDevelopers.rol.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.astroDevelopers.rol.logic.dto.RolDTO;
import co.edu.uniandes.csw.astroDevelopers.rol.persistence.api.IRolPersistence;
import co.edu.uniandes.csw.astroDevelopers.rol.persistence.entity.RolEntity;
import co.edu.uniandes.csw.astroDevelopers.rol.persistence.converter.RolConverter;
import static co.edu.uniandes.csw.astroDevelopers.util._TestUtil.*;

@RunWith(Arquillian.class)
public class RolPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(RolPersistence.class.getPackage())
				.addPackage(RolEntity.class.getPackage())
				.addPackage(IRolPersistence.class.getPackage())
                .addPackage(RolDTO.class.getPackage())
                .addPackage(RolConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IRolPersistence rolPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from RolEntity").executeUpdate();
	}

	private List<RolEntity> data=new ArrayList<RolEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			RolEntity entity=new RolEntity();
			entity.setName(generateRandom(String.class));
			entity.setInformacion(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createRolTest(){
		RolDTO dto=new RolDTO();
		dto.setName(generateRandom(String.class));
		dto.setInformacion(generateRandom(String.class));
		
		RolDTO result=rolPersistence.createRol(dto);
		
		Assert.assertNotNull(result);
		
		RolEntity entity=em.find(RolEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getInformacion(), entity.getInformacion());
	}
	
	@Test
	public void getRolsTest(){
		List<RolDTO> list=rolPersistence.getRols();
		Assert.assertEquals(list.size(), data.size());
        for(RolDTO dto:list){
        	boolean found=false;
            for(RolEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getRolTest(){
		RolEntity entity=data.get(0);
		RolDTO dto=rolPersistence.getRol(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getInformacion(), dto.getInformacion());
        
	}
	
	@Test
	public void deleteRolTest(){
		RolEntity entity=data.get(0);
		rolPersistence.deleteRol(entity.getId());
        RolEntity deleted=em.find(RolEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateRolTest(){
		RolEntity entity=data.get(0);
		
		RolDTO dto=new RolDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setInformacion(generateRandom(String.class));
		
		
		rolPersistence.updateRol(dto);
		
		
		RolEntity resp=em.find(RolEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getInformacion(), resp.getInformacion());	
	}
	
	
	
}