/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.charla.master.logic.ejb;

import co.edu.uniandes.csw.astroDevelopers.tag.logic.dto.TagDTO;
import co.edu.uniandes.csw.astroDevelopers.tag.persistence.api.ITagPersistence;
import co.edu.uniandes.csw.astroDevelopers.charla.logic.dto.CharlaDTO;
import co.edu.uniandes.csw.astroDevelopers.charla.master.logic.api._ICharlaMasterLogicService;
import co.edu.uniandes.csw.astroDevelopers.charla.master.logic.dto.CharlaMasterDTO;
import co.edu.uniandes.csw.astroDevelopers.charla.master.persistence.api.ICharlaMasterPersistence;
import co.edu.uniandes.csw.astroDevelopers.charla.master.persistence.entity.Charlatag_charlaEntity;
import co.edu.uniandes.csw.astroDevelopers.charla.persistence.api.ICharlaPersistence;
import javax.inject.Inject;

public abstract class _CharlaMasterLogicService implements _ICharlaMasterLogicService {

    @Inject
    protected ICharlaPersistence charlaPersistance;
    @Inject
    protected ICharlaMasterPersistence charlaMasterPersistance;
    @Inject
    protected ITagPersistence tagPersistance;

    public CharlaMasterDTO createMasterCharla(CharlaMasterDTO charla) {
        CharlaDTO persistedCharlaDTO = charlaPersistance.createCharla(charla.getCharlaEntity());
        if (charla.getCreatetag_charla() != null) {
            for (TagDTO tagDTO : charla.getCreatetag_charla()) {
                TagDTO createdTagDTO = tagPersistance.createTag(tagDTO);
                Charlatag_charlaEntity charlaTagEntity = new Charlatag_charlaEntity(persistedCharlaDTO.getId(), createdTagDTO.getId());
                charlaMasterPersistance.createCharlatag_charlaEntity(charlaTagEntity);
            }
        }
        // update tag
        if (charla.getUpdatetag_charla() != null) {
            for (TagDTO tagDTO : charla.getUpdatetag_charla()) {
                tagPersistance.updateTag(tagDTO);
                Charlatag_charlaEntity charlaTagEntity = new Charlatag_charlaEntity(persistedCharlaDTO.getId(), tagDTO.getId());
                charlaMasterPersistance.createCharlatag_charlaEntity(charlaTagEntity);
            }
        }
        return charla;
    }

    public CharlaMasterDTO getMasterCharla(Long id) {
        return charlaMasterPersistance.getCharla(id);
    }

    public void deleteMasterCharla(Long id) {
        charlaPersistance.deleteCharla(id);
    }

    public void updateMasterCharla(CharlaMasterDTO charla) {
        charlaPersistance.updateCharla(charla.getCharlaEntity());

        //---- FOR RELATIONSHIP
        // persist new tag
        if (charla.getCreatetag_charla() != null) {
            for (TagDTO tagDTO : charla.getCreatetag_charla()) {
                TagDTO createdTagDTO = tagPersistance.createTag(tagDTO);
                Charlatag_charlaEntity charlaTagEntity = new Charlatag_charlaEntity(charla.getCharlaEntity().getId(), createdTagDTO.getId());
                charlaMasterPersistance.createCharlatag_charlaEntity(charlaTagEntity);
            }
        }
        // update tag
        if (charla.getUpdatetag_charla() != null) {
            for (TagDTO tagDTO : charla.getUpdatetag_charla()) {
                tagPersistance.updateTag(tagDTO);
            }
        }
        // delete tag
        if (charla.getDeletetag_charla() != null) {
            for (TagDTO tagDTO : charla.getDeletetag_charla()) {
                charlaMasterPersistance.deleteCharlatag_charlaEntity(charla.getCharlaEntity().getId(), tagDTO.getId());
                tagPersistance.deleteTag(tagDTO.getId());
            }
        }
    }
}
