/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410261249

*/

package co.edu.uniandes.csw.astroDevelopers.taller.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.astroDevelopers.taller.logic.dto.TallerDTO;
import co.edu.uniandes.csw.astroDevelopers.taller.persistence.api.ITallerPersistence;
import co.edu.uniandes.csw.astroDevelopers.taller.persistence.entity.TallerEntity;
import co.edu.uniandes.csw.astroDevelopers.taller.persistence.converter.TallerConverter;
import static co.edu.uniandes.csw.astroDevelopers.util._TestUtil.*;

@RunWith(Arquillian.class)
public class TallerPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(TallerPersistence.class.getPackage())
				.addPackage(TallerEntity.class.getPackage())
				.addPackage(ITallerPersistence.class.getPackage())
                .addPackage(TallerDTO.class.getPackage())
                .addPackage(TallerConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private ITallerPersistence tallerPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from TallerEntity").executeUpdate();
	}

	private List<TallerEntity> data=new ArrayList<TallerEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			TallerEntity entity=new TallerEntity();
			entity.setName(generateRandom(String.class));
			entity.setInformacion(generateRandom(String.class));
			entity.setImagen(generateRandom(String.class));
			entity.setTitulo(generateRandom(String.class));
			entity.setTema(generateRandom(String.class));
			entity.setFechaEvento(generateRandom(Date.class));
			entity.setPublicacion(generateRandom(Date.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createTallerTest(){
		TallerDTO dto=new TallerDTO();
		dto.setName(generateRandom(String.class));
		dto.setInformacion(generateRandom(String.class));
		dto.setImagen(generateRandom(String.class));
		dto.setTitulo(generateRandom(String.class));
		dto.setTema(generateRandom(String.class));
dto.setFechaEvento(generateRandomDate());
dto.setPublicacion(generateRandomDate());
		
		TallerDTO result=tallerPersistence.createTaller(dto);
		
		Assert.assertNotNull(result);
		
		TallerEntity entity=em.find(TallerEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getInformacion(), entity.getInformacion());
		Assert.assertEquals(dto.getImagen(), entity.getImagen());
		Assert.assertEquals(dto.getTitulo(), entity.getTitulo());
		Assert.assertEquals(dto.getTema(), entity.getTema());
Assert.assertEquals(parseDate(dto.getFechaEvento()), entity.getFechaEvento());	
Assert.assertEquals(parseDate(dto.getPublicacion()), entity.getPublicacion());	
	}
	
	@Test
	public void getTallersTest(){
		List<TallerDTO> list=tallerPersistence.getTallers();
		Assert.assertEquals(list.size(), data.size());
        for(TallerDTO dto:list){
        	boolean found=false;
            for(TallerEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getTallerTest(){
		TallerEntity entity=data.get(0);
		TallerDTO dto=tallerPersistence.getTaller(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getInformacion(), dto.getInformacion());
		Assert.assertEquals(entity.getImagen(), dto.getImagen());
		Assert.assertEquals(entity.getTitulo(), dto.getTitulo());
		Assert.assertEquals(entity.getTema(), dto.getTema());
        
	}
	
	@Test
	public void deleteTallerTest(){
		TallerEntity entity=data.get(0);
		tallerPersistence.deleteTaller(entity.getId());
        TallerEntity deleted=em.find(TallerEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateTallerTest(){
		TallerEntity entity=data.get(0);
		
		TallerDTO dto=new TallerDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setInformacion(generateRandom(String.class));
		dto.setImagen(generateRandom(String.class));
		dto.setTitulo(generateRandom(String.class));
		dto.setTema(generateRandom(String.class));
dto.setFechaEvento(generateRandomDate());
dto.setPublicacion(generateRandomDate());
		
		
		tallerPersistence.updateTaller(dto);
		
		
		TallerEntity resp=em.find(TallerEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getInformacion(), resp.getInformacion());	
		Assert.assertEquals(dto.getImagen(), resp.getImagen());	
		Assert.assertEquals(dto.getTitulo(), resp.getTitulo());	
		Assert.assertEquals(dto.getTema(), resp.getTema());	
Assert.assertEquals(parseDate(dto.getFechaEvento()), resp.getFechaEvento());
Assert.assertEquals(parseDate(dto.getPublicacion()), resp.getPublicacion());
	}
	
	
	
}