/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.taller.master.persistence.entity;

import co.edu.uniandes.csw.astroDevelopers.usuario.persistence.entity.UsuarioEntity;
import co.edu.uniandes.csw.astroDevelopers.taller.persistence.entity.TallerEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(TallerusuarioEntityId.class)
@NamedQueries({
    @NamedQuery(name = "TallerusuarioEntity.getByMasterId", query = "SELECT  u FROM TallerusuarioEntity u WHERE u.tallerId=:tallerId"),
    @NamedQuery(name = "TallerusuarioEntity.deleteTallerusuarioEntity", query = "DELETE FROM TallerusuarioEntity u WHERE u.tallerId=:tallerId and  u.usuarioId=:usuarioId")
})
public class TallerusuarioEntity implements Serializable {

    @Id
    @Column(name = "tallerId")
    private Long tallerId;
    @Id
    @Column(name = "usuarioId")
    private Long usuarioId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "tallerId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity tallerIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "usuarioId", referencedColumnName = "id")
    @JoinFetch
    private UsuarioEntity usuarioIdEntity; 

    public TallerusuarioEntity() {
    }

    public TallerusuarioEntity(Long tallerId, Long usuarioId) {
        this.tallerId =tallerId;
        this.usuarioId = usuarioId;
    }

    public Long getTallerId() {
        return tallerId;
    }

    public void setTallerId(Long tallerId) {
        this.tallerId = tallerId;
    }

    public Long getUsuarioId() {
        return usuarioId;
    }

    public void setUsuarioId(Long usuarioId) {
        this.usuarioId = usuarioId;
    }

    public UsuarioEntity getTallerIdEntity() {
        return tallerIdEntity;
    }

    public void setTallerIdEntity(UsuarioEntity tallerIdEntity) {
        this.tallerIdEntity = tallerIdEntity;
    }

    public UsuarioEntity getUsuarioIdEntity() {
        return usuarioIdEntity;
    }

    public void setUsuarioIdEntity(UsuarioEntity usuarioIdEntity) {
        this.usuarioIdEntity = usuarioIdEntity;
    }

}
