/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410261249

*/

package co.edu.uniandes.csw.astroDevelopers.proyecto.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.astroDevelopers.proyecto.logic.dto.ProyectoDTO;
import co.edu.uniandes.csw.astroDevelopers.proyecto.persistence.api.IProyectoPersistence;
import co.edu.uniandes.csw.astroDevelopers.proyecto.persistence.entity.ProyectoEntity;
import co.edu.uniandes.csw.astroDevelopers.proyecto.persistence.converter.ProyectoConverter;
import static co.edu.uniandes.csw.astroDevelopers.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ProyectoPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ProyectoPersistence.class.getPackage())
				.addPackage(ProyectoEntity.class.getPackage())
				.addPackage(IProyectoPersistence.class.getPackage())
                .addPackage(ProyectoDTO.class.getPackage())
                .addPackage(ProyectoConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IProyectoPersistence proyectoPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ProyectoEntity").executeUpdate();
	}

	private List<ProyectoEntity> data=new ArrayList<ProyectoEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ProyectoEntity entity=new ProyectoEntity();
			entity.setName(generateRandom(String.class));
			entity.setTema(generateRandom(String.class));
			entity.setDescripcion(generateRandom(String.class));
			entity.setEstado(generateRandom(Integer.class));
			entity.setImagen(generateRandom(String.class));
			entity.setDemo(generateRandom(String.class));
			entity.setLema(generateRandom(String.class));
			entity.setEquipo_proyectoId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createProyectoTest(){
		ProyectoDTO dto=new ProyectoDTO();
		dto.setName(generateRandom(String.class));
		dto.setTema(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setEstado(generateRandom(Integer.class));
		dto.setImagen(generateRandom(String.class));
		dto.setDemo(generateRandom(String.class));
		dto.setLema(generateRandom(String.class));
		dto.setEquipo_proyectoId(generateRandom(Long.class));
		
		ProyectoDTO result=proyectoPersistence.createProyecto(dto);
		
		Assert.assertNotNull(result);
		
		ProyectoEntity entity=em.find(ProyectoEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getTema(), entity.getTema());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getEstado(), entity.getEstado());
		Assert.assertEquals(dto.getImagen(), entity.getImagen());
		Assert.assertEquals(dto.getDemo(), entity.getDemo());
		Assert.assertEquals(dto.getLema(), entity.getLema());
		Assert.assertEquals(dto.getEquipo_proyectoId(), entity.getEquipo_proyectoId());
	}
	
	@Test
	public void getProyectosTest(){
		List<ProyectoDTO> list=proyectoPersistence.getProyectos();
		Assert.assertEquals(list.size(), data.size());
        for(ProyectoDTO dto:list){
        	boolean found=false;
            for(ProyectoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getProyectoTest(){
		ProyectoEntity entity=data.get(0);
		ProyectoDTO dto=proyectoPersistence.getProyecto(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getTema(), dto.getTema());
		Assert.assertEquals(entity.getDescripcion(), dto.getDescripcion());
		Assert.assertEquals(entity.getEstado(), dto.getEstado());
		Assert.assertEquals(entity.getImagen(), dto.getImagen());
		Assert.assertEquals(entity.getDemo(), dto.getDemo());
		Assert.assertEquals(entity.getLema(), dto.getLema());
		Assert.assertEquals(entity.getEquipo_proyectoId(), dto.getEquipo_proyectoId());
        
	}
	
	@Test
	public void deleteProyectoTest(){
		ProyectoEntity entity=data.get(0);
		proyectoPersistence.deleteProyecto(entity.getId());
        ProyectoEntity deleted=em.find(ProyectoEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateProyectoTest(){
		ProyectoEntity entity=data.get(0);
		
		ProyectoDTO dto=new ProyectoDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setTema(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setEstado(generateRandom(Integer.class));
		dto.setImagen(generateRandom(String.class));
		dto.setDemo(generateRandom(String.class));
		dto.setLema(generateRandom(String.class));
		dto.setEquipo_proyectoId(generateRandom(Long.class));
		
		
		proyectoPersistence.updateProyecto(dto);
		
		
		ProyectoEntity resp=em.find(ProyectoEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getTema(), resp.getTema());	
		Assert.assertEquals(dto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(dto.getEstado(), resp.getEstado());	
		Assert.assertEquals(dto.getImagen(), resp.getImagen());	
		Assert.assertEquals(dto.getDemo(), resp.getDemo());	
		Assert.assertEquals(dto.getLema(), resp.getLema());	
		Assert.assertEquals(dto.getEquipo_proyectoId(), resp.getEquipo_proyectoId());	
	}
	
	
	
}