/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.charla.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.astroDevelopers.charla.logic.dto.CharlaDTO;
import co.edu.uniandes.csw.astroDevelopers.charla.logic.api.ICharlaLogicService;
import co.edu.uniandes.csw.astroDevelopers.charla.master.logic.api._ICharlaMasterLogicService;
import co.edu.uniandes.csw.astroDevelopers.charla.master.logic.dto.CharlaMasterDTO;
import co.edu.uniandes.csw.astroDevelopers.tag.logic.api.ITagLogicService;
import co.edu.uniandes.csw.astroDevelopers.tag.logic.dto.TagDTO;
import javax.inject.Inject;


public abstract class _CharlaMasterMockLogicService implements _ICharlaMasterLogicService {

    protected static ArrayList<CharlaMasterDTO> charlaMasterDtosList = new ArrayList<CharlaMasterDTO>() ;
    @Inject
    protected ITagLogicService tagPersistance;
    @Inject
    protected ICharlaLogicService charlaPersistance;

    public CharlaMasterDTO createMasterCharla(CharlaMasterDTO charla) {

        charlaPersistance.createCharla(charla.getCharlaEntity());
        for (TagDTO dto : charla.getCreatetag_charla()) {
            tagPersistance.createTag(dto);
        }
        charlaMasterDtosList.add(charla);
        return charla;
    }

    public CharlaMasterDTO getMasterCharla(Long id) {
        for (CharlaMasterDTO charlaMasterDTO : charlaMasterDtosList) {
            if (charlaMasterDTO.getCharlaEntity().getId() == id) {
                return charlaMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterCharla(Long id) {
        for (CharlaMasterDTO charlaMasterDTO : charlaMasterDtosList) {
            if (charlaMasterDTO.getCharlaEntity().getId() == id) {

                for (TagDTO dto : charlaMasterDTO.getCreatetag_charla()) {
                    tagPersistance.deleteTag(dto.getId());
                }
                charlaPersistance.deleteCharla(charlaMasterDTO.getId());
                charlaMasterDtosList.remove(charlaMasterDTO);
            }
        }

    }

    public void updateMasterCharla(CharlaMasterDTO charla) {

        // update Tag
        if (charla.getUpdatetag_charla() != null) {
            for (TagDTO dto : charla.getUpdatetag_charla()) {
                tagPersistance.updateTag(dto);
            }
        }
        // persist new Tag
        if (charla.getCreatetag_charla() != null) {
            for (TagDTO dto : charla.getCreatetag_charla()) {
                TagDTO persistedTagDTO = tagPersistance.createTag(dto);
                dto = persistedTagDTO;
            }
        }
        // delete Tag
        if (charla.getDeletetag_charla() != null) {
            for (TagDTO dto : charla.getDeletetag_charla()) {

                tagPersistance.deleteTag(dto.getId());
            }
        }
    }
}