/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.taller.master.persistence.entity;

import co.edu.uniandes.csw.astroDevelopers.tag.persistence.entity.TagEntity;
import co.edu.uniandes.csw.astroDevelopers.taller.persistence.entity.TallerEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(Tallertag_tallerEntityId.class)
@NamedQueries({
    @NamedQuery(name = "Tallertag_tallerEntity.getByMasterId", query = "SELECT  u FROM Tallertag_tallerEntity u WHERE u.tallerId=:tallerId"),
    @NamedQuery(name = "Tallertag_tallerEntity.deleteTallertag_tallerEntity", query = "DELETE FROM Tallertag_tallerEntity u WHERE u.tallerId=:tallerId and  u.tag_tallerId=:tag_tallerId")
})
public class Tallertag_tallerEntity implements Serializable {

    @Id
    @Column(name = "tallerId")
    private Long tallerId;
    @Id
    @Column(name = "tag_tallerId")
    private Long tag_tallerId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "tallerId", referencedColumnName = "id")
    @JoinFetch
    private TagEntity tallerIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "tag_tallerId", referencedColumnName = "id")
    @JoinFetch
    private TagEntity tag_tallerIdEntity; 

    public Tallertag_tallerEntity() {
    }

    public Tallertag_tallerEntity(Long tallerId, Long tag_tallerId) {
        this.tallerId =tallerId;
        this.tag_tallerId = tag_tallerId;
    }

    public Long getTallerId() {
        return tallerId;
    }

    public void setTallerId(Long tallerId) {
        this.tallerId = tallerId;
    }

    public Long getTag_tallerId() {
        return tag_tallerId;
    }

    public void setTag_tallerId(Long tag_tallerId) {
        this.tag_tallerId = tag_tallerId;
    }

    public TagEntity getTallerIdEntity() {
        return tallerIdEntity;
    }

    public void setTallerIdEntity(TagEntity tallerIdEntity) {
        this.tallerIdEntity = tallerIdEntity;
    }

    public TagEntity getTag_tallerIdEntity() {
        return tag_tallerIdEntity;
    }

    public void setTag_tallerIdEntity(TagEntity tag_tallerIdEntity) {
        this.tag_tallerIdEntity = tag_tallerIdEntity;
    }

}
