/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410261249

*/

package co.edu.uniandes.csw.astroDevelopers.solicitud.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.astroDevelopers.solicitud.logic.dto.SolicitudDTO;
import co.edu.uniandes.csw.astroDevelopers.solicitud.persistence.api.ISolicitudPersistence;
import co.edu.uniandes.csw.astroDevelopers.solicitud.persistence.entity.SolicitudEntity;
import co.edu.uniandes.csw.astroDevelopers.solicitud.persistence.converter.SolicitudConverter;
import static co.edu.uniandes.csw.astroDevelopers.util._TestUtil.*;

@RunWith(Arquillian.class)
public class SolicitudPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(SolicitudPersistence.class.getPackage())
				.addPackage(SolicitudEntity.class.getPackage())
				.addPackage(ISolicitudPersistence.class.getPackage())
                .addPackage(SolicitudDTO.class.getPackage())
                .addPackage(SolicitudConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private ISolicitudPersistence solicitudPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from SolicitudEntity").executeUpdate();
	}

	private List<SolicitudEntity> data=new ArrayList<SolicitudEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			SolicitudEntity entity=new SolicitudEntity();
			entity.setName(generateRandom(String.class));
			entity.setEmailPersona(generateRandom(String.class));
			entity.setHojaDeVida(generateRandom(String.class));
			entity.setComentario(generateRandom(String.class));
			entity.setNombreApellido(generateRandom(String.class));
			entity.setRol_solicitudId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createSolicitudTest(){
		SolicitudDTO dto=new SolicitudDTO();
		dto.setName(generateRandom(String.class));
		dto.setEmailPersona(generateRandom(String.class));
		dto.setHojaDeVida(generateRandom(String.class));
		dto.setComentario(generateRandom(String.class));
		dto.setNombreApellido(generateRandom(String.class));
		dto.setRol_solicitudId(generateRandom(Long.class));
		
		SolicitudDTO result=solicitudPersistence.createSolicitud(dto);
		
		Assert.assertNotNull(result);
		
		SolicitudEntity entity=em.find(SolicitudEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getEmailPersona(), entity.getEmailPersona());
		Assert.assertEquals(dto.getHojaDeVida(), entity.getHojaDeVida());
		Assert.assertEquals(dto.getComentario(), entity.getComentario());
		Assert.assertEquals(dto.getNombreApellido(), entity.getNombreApellido());
		Assert.assertEquals(dto.getRol_solicitudId(), entity.getRol_solicitudId());
	}
	
	@Test
	public void getSolicitudsTest(){
		List<SolicitudDTO> list=solicitudPersistence.getSolicituds();
		Assert.assertEquals(list.size(), data.size());
        for(SolicitudDTO dto:list){
        	boolean found=false;
            for(SolicitudEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getSolicitudTest(){
		SolicitudEntity entity=data.get(0);
		SolicitudDTO dto=solicitudPersistence.getSolicitud(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getEmailPersona(), dto.getEmailPersona());
		Assert.assertEquals(entity.getHojaDeVida(), dto.getHojaDeVida());
		Assert.assertEquals(entity.getComentario(), dto.getComentario());
		Assert.assertEquals(entity.getNombreApellido(), dto.getNombreApellido());
		Assert.assertEquals(entity.getRol_solicitudId(), dto.getRol_solicitudId());
        
	}
	
	@Test
	public void deleteSolicitudTest(){
		SolicitudEntity entity=data.get(0);
		solicitudPersistence.deleteSolicitud(entity.getId());
        SolicitudEntity deleted=em.find(SolicitudEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateSolicitudTest(){
		SolicitudEntity entity=data.get(0);
		
		SolicitudDTO dto=new SolicitudDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setEmailPersona(generateRandom(String.class));
		dto.setHojaDeVida(generateRandom(String.class));
		dto.setComentario(generateRandom(String.class));
		dto.setNombreApellido(generateRandom(String.class));
		dto.setRol_solicitudId(generateRandom(Long.class));
		
		
		solicitudPersistence.updateSolicitud(dto);
		
		
		SolicitudEntity resp=em.find(SolicitudEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getEmailPersona(), resp.getEmailPersona());	
		Assert.assertEquals(dto.getHojaDeVida(), resp.getHojaDeVida());	
		Assert.assertEquals(dto.getComentario(), resp.getComentario());	
		Assert.assertEquals(dto.getNombreApellido(), resp.getNombreApellido());	
		Assert.assertEquals(dto.getRol_solicitudId(), resp.getRol_solicitudId());	
	}
	
	
	
}