/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.solicitud.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.astroDevelopers.solicitud.logic.dto.SolicitudDTO;
import co.edu.uniandes.csw.astroDevelopers.solicitud.persistence.api._ISolicitudPersistence;
import co.edu.uniandes.csw.astroDevelopers.solicitud.persistence.converter.SolicitudConverter;
import co.edu.uniandes.csw.astroDevelopers.solicitud.persistence.entity.SolicitudEntity;

public abstract class _SolicitudPersistence implements _ISolicitudPersistence {

  	@PersistenceContext(unitName="KanuaUML12PU")
 
	protected EntityManager entityManager;
	
	public SolicitudDTO createSolicitud(SolicitudDTO solicitud) {
		SolicitudEntity entity=SolicitudConverter.persistenceDTO2Entity(solicitud);
		entityManager.persist(entity);
		return SolicitudConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<SolicitudDTO> getSolicituds() {
		Query q = entityManager.createQuery("select u from SolicitudEntity u");
		return SolicitudConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public SolicitudDTO getSolicitud(Long id) {
		return SolicitudConverter.entity2PersistenceDTO(entityManager.find(SolicitudEntity.class, id));
	}

	public void deleteSolicitud(Long id) {
		SolicitudEntity entity=entityManager.find(SolicitudEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateSolicitud(SolicitudDTO detail) {
		SolicitudEntity entity=entityManager.merge(SolicitudConverter.persistenceDTO2Entity(detail));
		SolicitudConverter.entity2PersistenceDTO(entity);
	}

}