/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.solicitud.persistence;

import co.edu.uniandes.csw.astroDevelopers.solicitud.logic.dto.SolicitudDTO;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.astroDevelopers.solicitud.persistence.api.ISolicitudPersistence;
import javax.ejb.LocalBean;

@Default
@Stateless 
@LocalBean
public class SolicitudPersistence extends _SolicitudPersistence  implements ISolicitudPersistence {
    
    public String crearSolicitud(String name, String lname, String email, String link, String rol, String comment) {
        SolicitudDTO s = new SolicitudDTO();
        s.setComentario(comment);
        s.setEmailPersona(email);
        s.setHojaDeVida(link);
        s.setName(name);
        s.setNombreApellido(lname);
        s.setRol_solicitudId(Long.parseLong(rol));
        
        SolicitudDTO n = createSolicitud(s);        
        
        return n.getId() + "";
    }

}