/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.solicitud.logic.dto;

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement 
public abstract class _SolicitudDTO {

	

	private Long id;
	

	private String name;
	

	private String emailPersona;
	

	private String hojaDeVida;
	

	private String comentario;
	

	private String nombreApellido;
	

	private Long rol_solicitudId;



	public Long getId() {
		return id;
	}
 
	public void setId(Long id) {
		this.id = id;
	}


	public String getName() {
		return name;
	}
 
	public void setName(String name) {
		this.name = name;
	}


	public String getEmailPersona() {
		return emailPersona;
	}
 
	public void setEmailPersona(String emailpersona) {
		this.emailPersona = emailpersona;
	}


	public String getHojaDeVida() {
		return hojaDeVida;
	}
 
	public void setHojaDeVida(String hojadevida) {
		this.hojaDeVida = hojadevida;
	}


	public String getComentario() {
		return comentario;
	}
 
	public void setComentario(String comentario) {
		this.comentario = comentario;
	}


	public String getNombreApellido() {
		return nombreApellido;
	}
 
	public void setNombreApellido(String nombreapellido) {
		this.nombreApellido = nombreapellido;
	}


	public Long getRol_solicitudId() {
		return rol_solicitudId;
	}
 
	public void setRol_solicitudId(Long rol_solicitudid) {
		this.rol_solicitudId = rol_solicitudid;
	}
	
}