/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.equipo.master.persistence.entity;

import co.edu.uniandes.csw.astroDevelopers.solicitud.persistence.entity.SolicitudEntity;
import co.edu.uniandes.csw.astroDevelopers.equipo.persistence.entity.EquipoEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(Equiposolicitud_proyectoEntityId.class)
@NamedQueries({
    @NamedQuery(name = "Equiposolicitud_proyectoEntity.getByMasterId", query = "SELECT  u FROM Equiposolicitud_proyectoEntity u WHERE u.equipoId=:equipoId"),
    @NamedQuery(name = "Equiposolicitud_proyectoEntity.deleteEquiposolicitud_proyectoEntity", query = "DELETE FROM Equiposolicitud_proyectoEntity u WHERE u.equipoId=:equipoId and  u.solicitud_proyectoId=:solicitud_proyectoId")
})
public class Equiposolicitud_proyectoEntity implements Serializable {

    @Id
    @Column(name = "equipoId")
    private Long equipoId;
    @Id
    @Column(name = "solicitud_proyectoId")
    private Long solicitud_proyectoId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "equipoId", referencedColumnName = "id")
    @JoinFetch
    private SolicitudEntity equipoIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "solicitud_proyectoId", referencedColumnName = "id")
    @JoinFetch
    private SolicitudEntity solicitud_proyectoIdEntity; 

    public Equiposolicitud_proyectoEntity() {
    }

    public Equiposolicitud_proyectoEntity(Long equipoId, Long solicitud_proyectoId) {
        this.equipoId =equipoId;
        this.solicitud_proyectoId = solicitud_proyectoId;
    }

    public Long getEquipoId() {
        return equipoId;
    }

    public void setEquipoId(Long equipoId) {
        this.equipoId = equipoId;
    }

    public Long getSolicitud_proyectoId() {
        return solicitud_proyectoId;
    }

    public void setSolicitud_proyectoId(Long solicitud_proyectoId) {
        this.solicitud_proyectoId = solicitud_proyectoId;
    }

    public SolicitudEntity getEquipoIdEntity() {
        return equipoIdEntity;
    }

    public void setEquipoIdEntity(SolicitudEntity equipoIdEntity) {
        this.equipoIdEntity = equipoIdEntity;
    }

    public SolicitudEntity getSolicitud_proyectoIdEntity() {
        return solicitud_proyectoIdEntity;
    }

    public void setSolicitud_proyectoIdEntity(SolicitudEntity solicitud_proyectoIdEntity) {
        this.solicitud_proyectoIdEntity = solicitud_proyectoIdEntity;
    }

}
