/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.proyecto.master.logic.dto;

import co.edu.uniandes.csw.astroDevelopers.tag.logic.dto.TagDTO;
import co.edu.uniandes.csw.astroDevelopers.objetivo.logic.dto.ObjetivoDTO;
import co.edu.uniandes.csw.astroDevelopers.proyecto.logic.dto.ProyectoDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _ProyectoMasterDTO {

 
    protected ProyectoDTO proyectoEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public ProyectoDTO getProyectoEntity() {
        return proyectoEntity;
    }

    public void setProyectoEntity(ProyectoDTO proyectoEntity) {
        this.proyectoEntity = proyectoEntity;
    }
    
    public List<TagDTO> createtag_proyecto;
    public List<TagDTO> updatetag_proyecto;
    public List<TagDTO> deletetag_proyecto;
    public List<TagDTO> listtag_proyecto;	
    public List<ObjetivoDTO> createobjetivo_proyecto;
    public List<ObjetivoDTO> updateobjetivo_proyecto;
    public List<ObjetivoDTO> deleteobjetivo_proyecto;
    public List<ObjetivoDTO> listobjetivo_proyecto;	
	
	
	
    public List<TagDTO> getCreatetag_proyecto(){ return createtag_proyecto; };
    public void setCreatetag_proyecto(List<TagDTO> createtag_proyecto){ this.createtag_proyecto=createtag_proyecto; };
    public List<TagDTO> getUpdatetag_proyecto(){ return updatetag_proyecto; };
    public void setUpdatetag_proyecto(List<TagDTO> updatetag_proyecto){ this.updatetag_proyecto=updatetag_proyecto; };
    public List<TagDTO> getDeletetag_proyecto(){ return deletetag_proyecto; };
    public void setDeletetag_proyecto(List<TagDTO> deletetag_proyecto){ this.deletetag_proyecto=deletetag_proyecto; };
    public List<TagDTO> getListtag_proyecto(){ return listtag_proyecto; };
    public void setListtag_proyecto(List<TagDTO> listtag_proyecto){ this.listtag_proyecto=listtag_proyecto; };	
    public List<ObjetivoDTO> getCreateobjetivo_proyecto(){ return createobjetivo_proyecto; };
    public void setCreateobjetivo_proyecto(List<ObjetivoDTO> createobjetivo_proyecto){ this.createobjetivo_proyecto=createobjetivo_proyecto; };
    public List<ObjetivoDTO> getUpdateobjetivo_proyecto(){ return updateobjetivo_proyecto; };
    public void setUpdateobjetivo_proyecto(List<ObjetivoDTO> updateobjetivo_proyecto){ this.updateobjetivo_proyecto=updateobjetivo_proyecto; };
    public List<ObjetivoDTO> getDeleteobjetivo_proyecto(){ return deleteobjetivo_proyecto; };
    public void setDeleteobjetivo_proyecto(List<ObjetivoDTO> deleteobjetivo_proyecto){ this.deleteobjetivo_proyecto=deleteobjetivo_proyecto; };
    public List<ObjetivoDTO> getListobjetivo_proyecto(){ return listobjetivo_proyecto; };
    public void setListobjetivo_proyecto(List<ObjetivoDTO> listobjetivo_proyecto){ this.listobjetivo_proyecto=listobjetivo_proyecto; };	
	
	
}

