/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410261249

*/

package co.edu.uniandes.csw.astroDevelopers.taller.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.astroDevelopers.taller.logic.dto.TallerDTO;
import co.edu.uniandes.csw.astroDevelopers.taller.logic.api.ITallerLogicService;
import co.edu.uniandes.csw.astroDevelopers.taller.persistence.TallerPersistence;
import co.edu.uniandes.csw.astroDevelopers.taller.persistence.api.ITallerPersistence;
import co.edu.uniandes.csw.astroDevelopers.taller.persistence.entity.TallerEntity;
import co.edu.uniandes.csw.astroDevelopers.taller.persistence.converter.TallerConverter;
import static co.edu.uniandes.csw.astroDevelopers.util._TestUtil.*;

@RunWith(Arquillian.class)
public class TallerLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(TallerLogicService.class.getPackage())
				.addPackage(ITallerLogicService.class.getPackage())
				.addPackage(TallerPersistence.class.getPackage())
				.addPackage(TallerEntity.class.getPackage())
				.addPackage(ITallerPersistence.class.getPackage())
                .addPackage(TallerDTO.class.getPackage())
                .addPackage(TallerConverter.class.getPackage())
                .addPackage(TallerEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private ITallerLogicService tallerLogicService;
	
	@Inject
	private ITallerPersistence tallerPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<TallerDTO> dtos=tallerPersistence.getTallers();
		for(TallerDTO dto:dtos){
			tallerPersistence.deleteTaller(dto.getId());
		}
	}

	private List<TallerDTO> data=new ArrayList<TallerDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			TallerDTO pdto=new TallerDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setInformacion(generateRandom(String.class));
			pdto.setImagen(generateRandom(String.class));
			pdto.setTitulo(generateRandom(String.class));
			pdto.setTema(generateRandom(String.class));
			pdto.setFechaEvento(generateRandomDate());
			pdto.setPublicacion(generateRandomDate());
			pdto=tallerPersistence.createTaller(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createTallerTest(){
		TallerDTO ldto=new TallerDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setInformacion(generateRandom(String.class));
		ldto.setImagen(generateRandom(String.class));
		ldto.setTitulo(generateRandom(String.class));
		ldto.setTema(generateRandom(String.class));
		ldto.setFechaEvento(generateRandomDate());
		ldto.setPublicacion(generateRandomDate());
		
		
		TallerDTO result=tallerLogicService.createTaller(ldto);
		
		Assert.assertNotNull(result);
		
		TallerDTO pdto=tallerPersistence.getTaller(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getInformacion(), pdto.getInformacion());	
		Assert.assertEquals(ldto.getImagen(), pdto.getImagen());	
		Assert.assertEquals(ldto.getTitulo(), pdto.getTitulo());	
		Assert.assertEquals(ldto.getTema(), pdto.getTema());	
		Assert.assertEquals(ldto.getFechaEvento(), pdto.getFechaEvento());	
		Assert.assertEquals(ldto.getPublicacion(), pdto.getPublicacion());	
	}
	
	@Test
	public void getTallersTest(){
		List<TallerDTO> list=tallerLogicService.getTallers();
		Assert.assertEquals(list.size(), data.size());
        for(TallerDTO ldto:list){
        	boolean found=false;
            for(TallerDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getTallerTest(){
		TallerDTO pdto=data.get(0);
		TallerDTO ldto=tallerLogicService.getTaller(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getInformacion(), ldto.getInformacion());
		Assert.assertEquals(pdto.getImagen(), ldto.getImagen());
		Assert.assertEquals(pdto.getTitulo(), ldto.getTitulo());
		Assert.assertEquals(pdto.getTema(), ldto.getTema());
		Assert.assertEquals(pdto.getFechaEvento(), ldto.getFechaEvento());
		Assert.assertEquals(pdto.getPublicacion(), ldto.getPublicacion());
        
	}
	
	@Test
	public void deleteTallerTest(){
		TallerDTO pdto=data.get(0);
		tallerLogicService.deleteTaller(pdto.getId());
        TallerDTO deleted=tallerPersistence.getTaller(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateTallerTest(){
		TallerDTO pdto=data.get(0);
		
		TallerDTO ldto=new TallerDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setInformacion(generateRandom(String.class));
		ldto.setImagen(generateRandom(String.class));
		ldto.setTitulo(generateRandom(String.class));
		ldto.setTema(generateRandom(String.class));
		ldto.setFechaEvento(generateRandomDate());
		ldto.setPublicacion(generateRandomDate());
		
		
		tallerLogicService.updateTaller(ldto);
		
		
		TallerDTO resp=tallerPersistence.getTaller(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getInformacion(), resp.getInformacion());	
		Assert.assertEquals(ldto.getImagen(), resp.getImagen());	
		Assert.assertEquals(ldto.getTitulo(), resp.getTitulo());	
		Assert.assertEquals(ldto.getTema(), resp.getTema());	
		Assert.assertEquals(ldto.getFechaEvento(), resp.getFechaEvento());	
		Assert.assertEquals(ldto.getPublicacion(), resp.getPublicacion());	
	}
	
	
	
}