/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.equipo.master.persistence;
import co.edu.uniandes.csw.astroDevelopers.solicitud.logic.dto.SolicitudDTO;
import co.edu.uniandes.csw.astroDevelopers.equipo.master.persistence.entity.Equiposolicitud_proyectoEntity;
import co.edu.uniandes.csw.astroDevelopers.solicitud.persistence.converter.SolicitudConverter;
import co.edu.uniandes.csw.astroDevelopers.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.astroDevelopers.equipo.master.persistence.entity.Equipousuario_equipoEntity;
import co.edu.uniandes.csw.astroDevelopers.usuario.persistence.converter.UsuarioConverter;
import co.edu.uniandes.csw.astroDevelopers.equipo.logic.dto.EquipoDTO;
import co.edu.uniandes.csw.astroDevelopers.equipo.master.logic.dto.EquipoMasterDTO;
import co.edu.uniandes.csw.astroDevelopers.equipo.master.persistence.api._IEquipoMasterPersistence;
import co.edu.uniandes.csw.astroDevelopers.equipo.persistence.api.IEquipoPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _EquipoMasterPersistence implements _IEquipoMasterPersistence {

  	@PersistenceContext(unitName="KanuaUML12PU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IEquipoPersistence equipoPersistence;  

    public EquipoMasterDTO getEquipo(Long equipoId) {
        EquipoMasterDTO equipoMasterDTO = new EquipoMasterDTO();
        EquipoDTO equipo = equipoPersistence.getEquipo(equipoId);
        equipoMasterDTO.setEquipoEntity(equipo);
        equipoMasterDTO.setListsolicitud_proyecto(getEquiposolicitud_proyectoEntityList(equipoId));
        equipoMasterDTO.setListusuario_equipo(getEquipousuario_equipoEntityList(equipoId));
        return equipoMasterDTO;
    }

    public Equiposolicitud_proyectoEntity createEquiposolicitud_proyectoEntity(Equiposolicitud_proyectoEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteEquiposolicitud_proyectoEntity(Long equipoId, Long solicitud_proyectoId) {
        Query q = entityManager.createNamedQuery("Equiposolicitud_proyectoEntity.deleteEquiposolicitud_proyectoEntity");
        q.setParameter("equipoId", equipoId);
        q.setParameter("solicitud_proyectoId", solicitud_proyectoId);
        q.executeUpdate();
    }

    public List<SolicitudDTO> getEquiposolicitud_proyectoEntityList(Long equipoId) {
        ArrayList<SolicitudDTO> resp = new ArrayList<SolicitudDTO>();
        Query q = entityManager.createNamedQuery("Equiposolicitud_proyectoEntity.getByMasterId");
        q.setParameter("equipoId",equipoId);
        List<Equiposolicitud_proyectoEntity> qResult =  q.getResultList();
        for (Equiposolicitud_proyectoEntity entity : qResult) { 
            if(entity.getSolicitud_proyectoIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(SolicitudConverter.entity2PersistenceDTO(entity.getSolicitud_proyectoIdEntity()));
        }
        return resp;
    }
    public Equipousuario_equipoEntity createEquipousuario_equipoEntity(Equipousuario_equipoEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteEquipousuario_equipoEntity(Long equipoId, Long usuario_equipoId) {
        Query q = entityManager.createNamedQuery("Equipousuario_equipoEntity.deleteEquipousuario_equipoEntity");
        q.setParameter("equipoId", equipoId);
        q.setParameter("usuario_equipoId", usuario_equipoId);
        q.executeUpdate();
    }

    public List<UsuarioDTO> getEquipousuario_equipoEntityList(Long equipoId) {
        ArrayList<UsuarioDTO> resp = new ArrayList<UsuarioDTO>();
        Query q = entityManager.createNamedQuery("Equipousuario_equipoEntity.getByMasterId");
        q.setParameter("equipoId",equipoId);
        List<Equipousuario_equipoEntity> qResult =  q.getResultList();
        for (Equipousuario_equipoEntity entity : qResult) { 
            if(entity.getUsuario_equipoIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(UsuarioConverter.entity2PersistenceDTO(entity.getUsuario_equipoIdEntity()));
        }
        return resp;
    }

}
