/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.charla.persistence.entity;

import java.util.Date;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.MappedSuperclass;

@MappedSuperclass
public abstract class _CharlaEntity {

	@Id
	@GeneratedValue(generator = "Charla")
	private Long id;
	private String name;
	private String titulo;
	private String informacion;
	private String link;
	@Temporal(TemporalType.DATE)
	private Date fechaEvento;
	private String imagen;
	@Temporal(TemporalType.DATE)
	private Date publicacion;

	public Long getId(){
		return id;
	}
	
	public void setId(Long id){
		this.id = id;
	}
	public String getName(){
		return name;
	}
	
	public void setName(String name){
		this.name = name;
	}
	public String getTitulo(){
		return titulo;
	}
	
	public void setTitulo(String titulo){
		this.titulo = titulo;
	}
	public String getInformacion(){
		return informacion;
	}
	
	public void setInformacion(String informacion){
		this.informacion = informacion;
	}
	public String getLink(){
		return link;
	}
	
	public void setLink(String link){
		this.link = link;
	}
	public Date getFechaEvento(){
		return fechaEvento;
	}
	
	public void setFechaEvento(Date fechaEvento){
		this.fechaEvento = fechaEvento;
	}
	public String getImagen(){
		return imagen;
	}
	
	public void setImagen(String imagen){
		this.imagen = imagen;
	}
	public Date getPublicacion(){
		return publicacion;
	}
	
	public void setPublicacion(Date publicacion){
		this.publicacion = publicacion;
	}
}