/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410261249

*/

package co.edu.uniandes.csw.astroDevelopers.equipo.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.astroDevelopers.equipo.logic.dto.EquipoDTO;
import co.edu.uniandes.csw.astroDevelopers.equipo.persistence.api.IEquipoPersistence;
import co.edu.uniandes.csw.astroDevelopers.equipo.persistence.entity.EquipoEntity;
import co.edu.uniandes.csw.astroDevelopers.equipo.persistence.converter.EquipoConverter;
import static co.edu.uniandes.csw.astroDevelopers.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EquipoPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EquipoPersistence.class.getPackage())
				.addPackage(EquipoEntity.class.getPackage())
				.addPackage(IEquipoPersistence.class.getPackage())
                .addPackage(EquipoDTO.class.getPackage())
                .addPackage(EquipoConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEquipoPersistence equipoPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from EquipoEntity").executeUpdate();
	}

	private List<EquipoEntity> data=new ArrayList<EquipoEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EquipoEntity entity=new EquipoEntity();
			entity.setName(generateRandom(String.class));
			entity.setEmail(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createEquipoTest(){
		EquipoDTO dto=new EquipoDTO();
		dto.setName(generateRandom(String.class));
		dto.setEmail(generateRandom(String.class));
		
		EquipoDTO result=equipoPersistence.createEquipo(dto);
		
		Assert.assertNotNull(result);
		
		EquipoEntity entity=em.find(EquipoEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getEmail(), entity.getEmail());
	}
	
	@Test
	public void getEquiposTest(){
		List<EquipoDTO> list=equipoPersistence.getEquipos();
		Assert.assertEquals(list.size(), data.size());
        for(EquipoDTO dto:list){
        	boolean found=false;
            for(EquipoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEquipoTest(){
		EquipoEntity entity=data.get(0);
		EquipoDTO dto=equipoPersistence.getEquipo(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getEmail(), dto.getEmail());
        
	}
	
	@Test
	public void deleteEquipoTest(){
		EquipoEntity entity=data.get(0);
		equipoPersistence.deleteEquipo(entity.getId());
        EquipoEntity deleted=em.find(EquipoEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEquipoTest(){
		EquipoEntity entity=data.get(0);
		
		EquipoDTO dto=new EquipoDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setEmail(generateRandom(String.class));
		
		
		equipoPersistence.updateEquipo(dto);
		
		
		EquipoEntity resp=em.find(EquipoEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getEmail(), resp.getEmail());	
	}
	
	
	
}