/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.objetivo.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.astroDevelopers.objetivo.logic.dto.ObjetivoDTO;
import co.edu.uniandes.csw.astroDevelopers.objetivo.persistence.api._IObjetivoPersistence;
import co.edu.uniandes.csw.astroDevelopers.objetivo.persistence.converter.ObjetivoConverter;
import co.edu.uniandes.csw.astroDevelopers.objetivo.persistence.entity.ObjetivoEntity;

public abstract class _ObjetivoPersistence implements _IObjetivoPersistence {

  	@PersistenceContext(unitName="KanuaUML12PU")
 
	protected EntityManager entityManager;
	
	public ObjetivoDTO createObjetivo(ObjetivoDTO objetivo) {
		ObjetivoEntity entity=ObjetivoConverter.persistenceDTO2Entity(objetivo);
		entityManager.persist(entity);
		return ObjetivoConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<ObjetivoDTO> getObjetivos() {
		Query q = entityManager.createQuery("select u from ObjetivoEntity u");
		return ObjetivoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public ObjetivoDTO getObjetivo(Long id) {
		return ObjetivoConverter.entity2PersistenceDTO(entityManager.find(ObjetivoEntity.class, id));
	}

	public void deleteObjetivo(Long id) {
		ObjetivoEntity entity=entityManager.find(ObjetivoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateObjetivo(ObjetivoDTO detail) {
		ObjetivoEntity entity=entityManager.merge(ObjetivoConverter.persistenceDTO2Entity(detail));
		ObjetivoConverter.entity2PersistenceDTO(entity);
	}

}