/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.noticia.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.astroDevelopers.noticia.logic.dto.NoticiaDTO;
import co.edu.uniandes.csw.astroDevelopers.noticia.persistence.entity.NoticiaEntity;

public abstract class _NoticiaConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static NoticiaDTO entity2PersistenceDTO(NoticiaEntity entity){
		if (entity != null) {
			NoticiaDTO dto = new NoticiaDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setImagen(entity.getImagen());
					dto.setTitulo(entity.getTitulo());
 
			    if(entity.getFecha() != null){
					dto.setFecha(DATE_FORMAT.format(entity.getFecha()));
				}	
					dto.setDescripcion(entity.getDescripcion());
					dto.setTema(entity.getTema());
			return dto;
		}else{
			return null;
		}
	}
	
	public static NoticiaEntity persistenceDTO2Entity(NoticiaDTO dto){
		if(dto!=null){
			NoticiaEntity entity=new NoticiaEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setImagen(dto.getImagen());
			
					entity.setTitulo(dto.getTitulo());
			
 
			      try{ 
			        if(dto.getFecha() != null){
						entity.setFecha(DATE_FORMAT.parse(dto.getFecha()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_NoticiaConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setDescripcion(dto.getDescripcion());
			
					entity.setTema(dto.getTema());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<NoticiaDTO> entity2PersistenceDTOList(List<NoticiaEntity> entities){
		List<NoticiaDTO> dtos=new ArrayList<NoticiaDTO>();
		for(NoticiaEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<NoticiaEntity> persistenceDTO2EntityList(List<NoticiaDTO> dtos){
		List<NoticiaEntity> entities=new ArrayList<NoticiaEntity>();
		for(NoticiaDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}