 
/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.proyecto.master.logic.ejb;

import co.edu.uniandes.csw.astroDevelopers.proyecto.master.logic.api.IProyectoMasterLogicService;
import java.util.Properties;
import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

@Default
@Stateless
@LocalBean
public class ProyectoMasterLogicService extends _ProyectoMasterLogicService implements IProyectoMasterLogicService {

    public String buscarProyectosPorTag(String tag){
        return proyectoMasterPersistance.buscarProyectosPorTag(tag);
    }
    
    public String procesarContacto(String name, String email, String text, String id_equipo) {
        String form = "From " + name + "." + text + ".\n" + "Email: " + email;
        return (sendTemplateEmail(form, id_equipo))? "SUCCESS" : "FAIL";
    }
        
    public boolean realizarSolicitud(String name, String lname, String email, String link, String rol, 
            String comment, String id) {
        boolean ans = false;
        return ans;
    }
    
    public boolean sendTemplateEmail(String text, String id_equipo) {
        
        boolean ans = true;

       Properties props = new Properties();  
       props.put("mail.smtp.host", "smtp.gmail.com");  
       props.put("mail.smtp.auth", "true");  
       props.put("mail.debug", "true");  
       props.put("mail.smtp.port", 25);  
       props.put("mail.smtp.socketFactory.port", 25);  
       props.put("mail.smtp.starttls.enable", "true");
       props.put("mail.transport.protocol", "smtp");
       Session mailSession = null;
       
       mailSession = Session.getInstance(props,  
               new javax.mail.Authenticator() {  
           protected PasswordAuthentication getPasswordAuthentication() {  
               return new PasswordAuthentication("astrodevelopers14", "Astrodevelopers2014");  
           }  
       });  


       try {

           Transport transport = mailSession.getTransport();

           MimeMessage message = new MimeMessage(mailSession);

           message.setSubject("PRUEBA");
           message.setFrom(new InternetAddress("astrodevelopers14@gmail.com"));
           proyectoMasterPersistance.emailsId(text);
           String []to = new String[]{"cd.bedoya212@uniandes.edu.co", "sc.valencia606@uniandes.edu.co"};
           message.addRecipient(Message.RecipientType.TO, new InternetAddress(to[0]));
           String body = text;
           message.setContent(body,"text/html");
           transport.connect();
           transport.sendMessage(message,message.getRecipients(Message.RecipientType.TO));
           transport.close();
       } catch (Exception exception) {
           exception.printStackTrace();
       }
       
       return ans;
   }

    

}