/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.equipo.master.logic.dto;

import co.edu.uniandes.csw.astroDevelopers.solicitud.logic.dto.SolicitudDTO;
import co.edu.uniandes.csw.astroDevelopers.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.astroDevelopers.equipo.logic.dto.EquipoDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _EquipoMasterDTO {

 
    protected EquipoDTO equipoEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public EquipoDTO getEquipoEntity() {
        return equipoEntity;
    }

    public void setEquipoEntity(EquipoDTO equipoEntity) {
        this.equipoEntity = equipoEntity;
    }
    
    public List<SolicitudDTO> createsolicitud_proyecto;
    public List<SolicitudDTO> updatesolicitud_proyecto;
    public List<SolicitudDTO> deletesolicitud_proyecto;
    public List<SolicitudDTO> listsolicitud_proyecto;	
    public List<UsuarioDTO> createusuario_equipo;
    public List<UsuarioDTO> updateusuario_equipo;
    public List<UsuarioDTO> deleteusuario_equipo;
    public List<UsuarioDTO> listusuario_equipo;	
	
	
	
    public List<SolicitudDTO> getCreatesolicitud_proyecto(){ return createsolicitud_proyecto; };
    public void setCreatesolicitud_proyecto(List<SolicitudDTO> createsolicitud_proyecto){ this.createsolicitud_proyecto=createsolicitud_proyecto; };
    public List<SolicitudDTO> getUpdatesolicitud_proyecto(){ return updatesolicitud_proyecto; };
    public void setUpdatesolicitud_proyecto(List<SolicitudDTO> updatesolicitud_proyecto){ this.updatesolicitud_proyecto=updatesolicitud_proyecto; };
    public List<SolicitudDTO> getDeletesolicitud_proyecto(){ return deletesolicitud_proyecto; };
    public void setDeletesolicitud_proyecto(List<SolicitudDTO> deletesolicitud_proyecto){ this.deletesolicitud_proyecto=deletesolicitud_proyecto; };
    public List<SolicitudDTO> getListsolicitud_proyecto(){ return listsolicitud_proyecto; };
    public void setListsolicitud_proyecto(List<SolicitudDTO> listsolicitud_proyecto){ this.listsolicitud_proyecto=listsolicitud_proyecto; };	
    public List<UsuarioDTO> getCreateusuario_equipo(){ return createusuario_equipo; };
    public void setCreateusuario_equipo(List<UsuarioDTO> createusuario_equipo){ this.createusuario_equipo=createusuario_equipo; };
    public List<UsuarioDTO> getUpdateusuario_equipo(){ return updateusuario_equipo; };
    public void setUpdateusuario_equipo(List<UsuarioDTO> updateusuario_equipo){ this.updateusuario_equipo=updateusuario_equipo; };
    public List<UsuarioDTO> getDeleteusuario_equipo(){ return deleteusuario_equipo; };
    public void setDeleteusuario_equipo(List<UsuarioDTO> deleteusuario_equipo){ this.deleteusuario_equipo=deleteusuario_equipo; };
    public List<UsuarioDTO> getListusuario_equipo(){ return listusuario_equipo; };
    public void setListusuario_equipo(List<UsuarioDTO> listusuario_equipo){ this.listusuario_equipo=listusuario_equipo; };	
	
	
}

