/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.taller.master.persistence;
import co.edu.uniandes.csw.astroDevelopers.tag.logic.dto.TagDTO;
import co.edu.uniandes.csw.astroDevelopers.taller.master.persistence.entity.Tallertag_tallerEntity;
import co.edu.uniandes.csw.astroDevelopers.tag.persistence.converter.TagConverter;
import co.edu.uniandes.csw.astroDevelopers.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.astroDevelopers.taller.master.persistence.entity.TallerusuarioEntity;
import co.edu.uniandes.csw.astroDevelopers.usuario.persistence.converter.UsuarioConverter;
import co.edu.uniandes.csw.astroDevelopers.taller.logic.dto.TallerDTO;
import co.edu.uniandes.csw.astroDevelopers.taller.master.logic.dto.TallerMasterDTO;
import co.edu.uniandes.csw.astroDevelopers.taller.master.persistence.api._ITallerMasterPersistence;
import co.edu.uniandes.csw.astroDevelopers.taller.persistence.api.ITallerPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _TallerMasterPersistence implements _ITallerMasterPersistence {

  	@PersistenceContext(unitName="KanuaUML12PU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected ITallerPersistence tallerPersistence;  

    public TallerMasterDTO getTaller(Long tallerId) {
        TallerMasterDTO tallerMasterDTO = new TallerMasterDTO();
        TallerDTO taller = tallerPersistence.getTaller(tallerId);
        tallerMasterDTO.setTallerEntity(taller);
        tallerMasterDTO.setListtag_taller(getTallertag_tallerEntityList(tallerId));
        tallerMasterDTO.setListusuario(getTallerusuarioEntityList(tallerId));
        return tallerMasterDTO;
    }

    public Tallertag_tallerEntity createTallertag_tallerEntity(Tallertag_tallerEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteTallertag_tallerEntity(Long tallerId, Long tag_tallerId) {
        Query q = entityManager.createNamedQuery("Tallertag_tallerEntity.deleteTallertag_tallerEntity");
        q.setParameter("tallerId", tallerId);
        q.setParameter("tag_tallerId", tag_tallerId);
        q.executeUpdate();
    }

    public List<TagDTO> getTallertag_tallerEntityList(Long tallerId) {
        ArrayList<TagDTO> resp = new ArrayList<TagDTO>();
        Query q = entityManager.createNamedQuery("Tallertag_tallerEntity.getByMasterId");
        q.setParameter("tallerId",tallerId);
        List<Tallertag_tallerEntity> qResult =  q.getResultList();
        for (Tallertag_tallerEntity entity : qResult) { 
            if(entity.getTag_tallerIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(TagConverter.entity2PersistenceDTO(entity.getTag_tallerIdEntity()));
        }
        return resp;
    }
    public TallerusuarioEntity createTallerusuarioEntity(TallerusuarioEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteTallerusuarioEntity(Long tallerId, Long usuarioId) {
        Query q = entityManager.createNamedQuery("TallerusuarioEntity.deleteTallerusuarioEntity");
        q.setParameter("tallerId", tallerId);
        q.setParameter("usuarioId", usuarioId);
        q.executeUpdate();
    }

    public List<UsuarioDTO> getTallerusuarioEntityList(Long tallerId) {
        ArrayList<UsuarioDTO> resp = new ArrayList<UsuarioDTO>();
        Query q = entityManager.createNamedQuery("TallerusuarioEntity.getByMasterId");
        q.setParameter("tallerId",tallerId);
        List<TallerusuarioEntity> qResult =  q.getResultList();
        for (TallerusuarioEntity entity : qResult) { 
            if(entity.getUsuarioIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(UsuarioConverter.entity2PersistenceDTO(entity.getUsuarioIdEntity()));
        }
        return resp;
    }

}
