/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.noticia.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.astroDevelopers.noticia.logic.dto.NoticiaDTO;
import co.edu.uniandes.csw.astroDevelopers.noticia.persistence.api._INoticiaPersistence;
import co.edu.uniandes.csw.astroDevelopers.noticia.persistence.converter.NoticiaConverter;
import co.edu.uniandes.csw.astroDevelopers.noticia.persistence.entity.NoticiaEntity;

public abstract class _NoticiaPersistence implements _INoticiaPersistence {

  	@PersistenceContext(unitName="KanuaUML12PU")
 
	protected EntityManager entityManager;
	
	public NoticiaDTO createNoticia(NoticiaDTO noticia) {
		NoticiaEntity entity=NoticiaConverter.persistenceDTO2Entity(noticia);
		entityManager.persist(entity);
		return NoticiaConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<NoticiaDTO> getNoticias() {
		Query q = entityManager.createQuery("select u from NoticiaEntity u");
		return NoticiaConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public NoticiaDTO getNoticia(Long id) {
		return NoticiaConverter.entity2PersistenceDTO(entityManager.find(NoticiaEntity.class, id));
	}

	public void deleteNoticia(Long id) {
		NoticiaEntity entity=entityManager.find(NoticiaEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateNoticia(NoticiaDTO detail) {
		NoticiaEntity entity=entityManager.merge(NoticiaConverter.persistenceDTO2Entity(detail));
		NoticiaConverter.entity2PersistenceDTO(entity);
	}

}