/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.taller.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.astroDevelopers.taller.logic.dto.TallerDTO;
import co.edu.uniandes.csw.astroDevelopers.taller.logic.api.ITallerLogicService;
import co.edu.uniandes.csw.astroDevelopers.taller.master.logic.api._ITallerMasterLogicService;
import co.edu.uniandes.csw.astroDevelopers.taller.master.logic.dto.TallerMasterDTO;
import co.edu.uniandes.csw.astroDevelopers.usuario.logic.api.IUsuarioLogicService;
import co.edu.uniandes.csw.astroDevelopers.tag.logic.api.ITagLogicService;
import co.edu.uniandes.csw.astroDevelopers.usuario.logic.dto.UsuarioDTO;
import co.edu.uniandes.csw.astroDevelopers.tag.logic.dto.TagDTO;
import javax.inject.Inject;


public abstract class _TallerMasterMockLogicService implements _ITallerMasterLogicService {

    protected static ArrayList<TallerMasterDTO> tallerMasterDtosList = new ArrayList<TallerMasterDTO>() ;
    @Inject
    protected IUsuarioLogicService usuarioPersistance;
    @Inject
    protected ITagLogicService tagPersistance;
    @Inject
    protected ITallerLogicService tallerPersistance;

    public TallerMasterDTO createMasterTaller(TallerMasterDTO taller) {

        tallerPersistance.createTaller(taller.getTallerEntity());
        for (TagDTO dto : taller.getCreatetag_taller()) {
            tagPersistance.createTag(dto);
        }
        for (UsuarioDTO dto : taller.getCreateusuario()) {
            usuarioPersistance.createUsuario(dto);
        }
        tallerMasterDtosList.add(taller);
        return taller;
    }

    public TallerMasterDTO getMasterTaller(Long id) {
        for (TallerMasterDTO tallerMasterDTO : tallerMasterDtosList) {
            if (tallerMasterDTO.getTallerEntity().getId() == id) {
                return tallerMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterTaller(Long id) {
        for (TallerMasterDTO tallerMasterDTO : tallerMasterDtosList) {
            if (tallerMasterDTO.getTallerEntity().getId() == id) {

                for (TagDTO dto : tallerMasterDTO.getCreatetag_taller()) {
                    tagPersistance.deleteTag(dto.getId());
                }
                tallerPersistance.deleteTaller(tallerMasterDTO.getId());
                tallerMasterDtosList.remove(tallerMasterDTO);
                for (UsuarioDTO dto : tallerMasterDTO.getCreateusuario()) {
                    usuarioPersistance.deleteUsuario(dto.getId());
                }
                tallerPersistance.deleteTaller(tallerMasterDTO.getId());
                tallerMasterDtosList.remove(tallerMasterDTO);
            }
        }

    }

    public void updateMasterTaller(TallerMasterDTO taller) {

        // update Tag
        if (taller.getUpdatetag_taller() != null) {
            for (TagDTO dto : taller.getUpdatetag_taller()) {
                tagPersistance.updateTag(dto);
            }
        }
        // persist new Tag
        if (taller.getCreatetag_taller() != null) {
            for (TagDTO dto : taller.getCreatetag_taller()) {
                TagDTO persistedTagDTO = tagPersistance.createTag(dto);
                dto = persistedTagDTO;
            }
        }
        // delete Tag
        if (taller.getDeletetag_taller() != null) {
            for (TagDTO dto : taller.getDeletetag_taller()) {

                tagPersistance.deleteTag(dto.getId());
            }
        }
        // update Usuario
        if (taller.getUpdateusuario() != null) {
            for (UsuarioDTO dto : taller.getUpdateusuario()) {
                usuarioPersistance.updateUsuario(dto);
            }
        }
        // persist new Usuario
        if (taller.getCreateusuario() != null) {
            for (UsuarioDTO dto : taller.getCreateusuario()) {
                UsuarioDTO persistedUsuarioDTO = usuarioPersistance.createUsuario(dto);
                dto = persistedUsuarioDTO;
            }
        }
        // delete Usuario
        if (taller.getDeleteusuario() != null) {
            for (UsuarioDTO dto : taller.getDeleteusuario()) {

                usuarioPersistance.deleteUsuario(dto.getId());
            }
        }
    }
}