/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.objetivo.service;

import java.util.List;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.inject.Inject;

import co.edu.uniandes.csw.astroDevelopers.objetivo.logic.api.IObjetivoLogicService;
import co.edu.uniandes.csw.astroDevelopers.objetivo.logic.dto.ObjetivoDTO;


public abstract class _ObjetivoService {

	@Inject
	protected IObjetivoLogicService objetivoLogicService;
	
	@POST
	public ObjetivoDTO createObjetivo(ObjetivoDTO objetivo){
		return objetivoLogicService.createObjetivo(objetivo);
	}
	
	@DELETE
	@Path("{id}")
	public void deleteObjetivo(@PathParam("id") Long id){
		objetivoLogicService.deleteObjetivo(id);
	}
	
	@GET
	public List<ObjetivoDTO> getObjetivos(){
		return objetivoLogicService.getObjetivos();
	}
	
	@GET
	@Path("{id}")
	public ObjetivoDTO getObjetivo(@PathParam("id") Long id){
		return objetivoLogicService.getObjetivo(id);
	}
	
	@PUT
    @Path("{id}")
	public void updateObjetivo(@PathParam("id") Long id, ObjetivoDTO objetivo){
		objetivoLogicService.updateObjetivo(objetivo);
	}
	
}