/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410261249

*/

package co.edu.uniandes.csw.astroDevelopers.objetivo.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.astroDevelopers.objetivo.logic.dto.ObjetivoDTO;
import co.edu.uniandes.csw.astroDevelopers.objetivo.logic.api.IObjetivoLogicService;
import co.edu.uniandes.csw.astroDevelopers.objetivo.persistence.ObjetivoPersistence;
import co.edu.uniandes.csw.astroDevelopers.objetivo.persistence.api.IObjetivoPersistence;
import co.edu.uniandes.csw.astroDevelopers.objetivo.persistence.entity.ObjetivoEntity;
import co.edu.uniandes.csw.astroDevelopers.objetivo.persistence.converter.ObjetivoConverter;
import static co.edu.uniandes.csw.astroDevelopers.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ObjetivoLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ObjetivoLogicService.class.getPackage())
				.addPackage(IObjetivoLogicService.class.getPackage())
				.addPackage(ObjetivoPersistence.class.getPackage())
				.addPackage(ObjetivoEntity.class.getPackage())
				.addPackage(IObjetivoPersistence.class.getPackage())
                .addPackage(ObjetivoDTO.class.getPackage())
                .addPackage(ObjetivoConverter.class.getPackage())
                .addPackage(ObjetivoEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IObjetivoLogicService objetivoLogicService;
	
	@Inject
	private IObjetivoPersistence objetivoPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<ObjetivoDTO> dtos=objetivoPersistence.getObjetivos();
		for(ObjetivoDTO dto:dtos){
			objetivoPersistence.deleteObjetivo(dto.getId());
		}
	}

	private List<ObjetivoDTO> data=new ArrayList<ObjetivoDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ObjetivoDTO pdto=new ObjetivoDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setDescripcion(generateRandom(String.class));
			pdto=objetivoPersistence.createObjetivo(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createObjetivoTest(){
		ObjetivoDTO ldto=new ObjetivoDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		
		
		ObjetivoDTO result=objetivoLogicService.createObjetivo(ldto);
		
		Assert.assertNotNull(result);
		
		ObjetivoDTO pdto=objetivoPersistence.getObjetivo(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getDescripcion(), pdto.getDescripcion());	
	}
	
	@Test
	public void getObjetivosTest(){
		List<ObjetivoDTO> list=objetivoLogicService.getObjetivos();
		Assert.assertEquals(list.size(), data.size());
        for(ObjetivoDTO ldto:list){
        	boolean found=false;
            for(ObjetivoDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getObjetivoTest(){
		ObjetivoDTO pdto=data.get(0);
		ObjetivoDTO ldto=objetivoLogicService.getObjetivo(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getDescripcion(), ldto.getDescripcion());
        
	}
	
	@Test
	public void deleteObjetivoTest(){
		ObjetivoDTO pdto=data.get(0);
		objetivoLogicService.deleteObjetivo(pdto.getId());
        ObjetivoDTO deleted=objetivoPersistence.getObjetivo(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateObjetivoTest(){
		ObjetivoDTO pdto=data.get(0);
		
		ObjetivoDTO ldto=new ObjetivoDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		
		
		objetivoLogicService.updateObjetivo(ldto);
		
		
		ObjetivoDTO resp=objetivoPersistence.getObjetivo(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getDescripcion(), resp.getDescripcion());	
	}
	
	
	
	
}