/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['model/_tallerModel'], function() {
    App.Model.TallerModel = App.Model._TallerModel.extend({

 	validate: function(attrs,options){
            var ln= attrs.imagen.toString();
            var en= ln.search("http://");
            var validationMessage = "";
            if(!attrs.name){
                validationMessage = "El nombre no puede ser vacio. ";
            }
            if(!attrs.informacion)
            {
                validationMessage+= "La informacion no puede ser vacia. ";
            }
            if(en===-1||!attrs.imagen)
            {
                validationMessage+= "La imagen no puede ser vacia o no es valida. ";
            }
            if(!attrs.tema)
            {
                validationMessage+= "El tema no puede ser vacio. ";
                
            }
            if(!attrs.titulo)
            {
                validationMessage+= "El titulo no puede ser vacio. ";
            }
            
            if(validationMessage.length>0){
               return validationMessage;
            }
            
        }

    });

    App.Model.TallerList = App.Model._TallerList.extend({
        model: App.Model.TallerModel
    });

    return  App.Model.TallerModel;

});