/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.noticia.master.logic.ejb;

import co.edu.uniandes.csw.astroDevelopers.tag.logic.dto.TagDTO;
import co.edu.uniandes.csw.astroDevelopers.tag.persistence.api.ITagPersistence;
import co.edu.uniandes.csw.astroDevelopers.noticia.logic.dto.NoticiaDTO;
import co.edu.uniandes.csw.astroDevelopers.noticia.master.logic.api._INoticiaMasterLogicService;
import co.edu.uniandes.csw.astroDevelopers.noticia.master.logic.dto.NoticiaMasterDTO;
import co.edu.uniandes.csw.astroDevelopers.noticia.master.persistence.api.INoticiaMasterPersistence;
import co.edu.uniandes.csw.astroDevelopers.noticia.master.persistence.entity.Noticiatag_noticiaEntity;
import co.edu.uniandes.csw.astroDevelopers.noticia.persistence.api.INoticiaPersistence;
import javax.inject.Inject;

public abstract class _NoticiaMasterLogicService implements _INoticiaMasterLogicService {

    @Inject
    protected INoticiaPersistence noticiaPersistance;
    @Inject
    protected INoticiaMasterPersistence noticiaMasterPersistance;
    @Inject
    protected ITagPersistence tagPersistance;

    public NoticiaMasterDTO createMasterNoticia(NoticiaMasterDTO noticia) {
        NoticiaDTO persistedNoticiaDTO = noticiaPersistance.createNoticia(noticia.getNoticiaEntity());
        if (noticia.getCreatetag_noticia() != null) {
            for (TagDTO tagDTO : noticia.getCreatetag_noticia()) {
                TagDTO createdTagDTO = tagPersistance.createTag(tagDTO);
                Noticiatag_noticiaEntity noticiaTagEntity = new Noticiatag_noticiaEntity(persistedNoticiaDTO.getId(), createdTagDTO.getId());
                noticiaMasterPersistance.createNoticiatag_noticiaEntity(noticiaTagEntity);
            }
        }
        // update tag
        if (noticia.getUpdatetag_noticia() != null) {
            for (TagDTO tagDTO : noticia.getUpdatetag_noticia()) {
                tagPersistance.updateTag(tagDTO);
                Noticiatag_noticiaEntity noticiaTagEntity = new Noticiatag_noticiaEntity(persistedNoticiaDTO.getId(), tagDTO.getId());
                noticiaMasterPersistance.createNoticiatag_noticiaEntity(noticiaTagEntity);
            }
        }
        return noticia;
    }

    public NoticiaMasterDTO getMasterNoticia(Long id) {
        return noticiaMasterPersistance.getNoticia(id);
    }

    public void deleteMasterNoticia(Long id) {
        noticiaPersistance.deleteNoticia(id);
    }

    public void updateMasterNoticia(NoticiaMasterDTO noticia) {
        noticiaPersistance.updateNoticia(noticia.getNoticiaEntity());

        //---- FOR RELATIONSHIP
        // delete tag
        if (noticia.getDeletetag_noticia() != null) {
            for (TagDTO tagDTO : noticia.getDeletetag_noticia()) {
                noticiaMasterPersistance.deleteNoticiatag_noticiaEntity(noticia.getNoticiaEntity().getId(), tagDTO.getId());
            }
        }
        // persist new tag
        if (noticia.getCreatetag_noticia() != null) {
            for (TagDTO tagDTO : noticia.getCreatetag_noticia()) {
                Noticiatag_noticiaEntity noticiaTagEntity = new Noticiatag_noticiaEntity(noticia.getNoticiaEntity().getId(), tagDTO.getId());
                noticiaMasterPersistance.createNoticiatag_noticiaEntity(noticiaTagEntity);
            }
        }
        // update tag
        if (noticia.getUpdatetag_noticia() != null) {
            for (TagDTO tagDTO : noticia.getUpdatetag_noticia()) {
                noticiaMasterPersistance.deleteNoticiatag_noticiaEntity(noticia.getNoticiaEntity().getId(), tagDTO.getId());
                tagPersistance.updateTag(tagDTO);
                Noticiatag_noticiaEntity noticiaTagEntity = new Noticiatag_noticiaEntity(noticia.getId(), tagDTO.getId());
                noticiaMasterPersistance.createNoticiatag_noticiaEntity(noticiaTagEntity);
                
            }
        }
    }
}
