/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.astroDevelopers.proyecto.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.astroDevelopers.proyecto.logic.dto.ProyectoDTO;
import co.edu.uniandes.csw.astroDevelopers.proyecto.persistence.entity.ProyectoEntity;

public abstract class _ProyectoConverter {

	public static ProyectoDTO entity2PersistenceDTO(ProyectoEntity entity){
		if (entity != null) {
			ProyectoDTO dto = new ProyectoDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setTema(entity.getTema());
					dto.setDescripcion(entity.getDescripcion());
					dto.setEstado(entity.getEstado());
					dto.setImagen(entity.getImagen());
					dto.setDemo(entity.getDemo());
					dto.setLema(entity.getLema());
					dto.setEquipo_proyectoId(entity.getEquipo_proyectoId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static ProyectoEntity persistenceDTO2Entity(ProyectoDTO dto){
		if(dto!=null){
			ProyectoEntity entity=new ProyectoEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setTema(dto.getTema());
			
					entity.setDescripcion(dto.getDescripcion());
			
					entity.setEstado(dto.getEstado());
			
					entity.setImagen(dto.getImagen());
			
					entity.setDemo(dto.getDemo());
			
					entity.setLema(dto.getLema());
			
					entity.setEquipo_proyectoId(dto.getEquipo_proyectoId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<ProyectoDTO> entity2PersistenceDTOList(List<ProyectoEntity> entities){
		List<ProyectoDTO> dtos=new ArrayList<ProyectoDTO>();
		for(ProyectoEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<ProyectoEntity> persistenceDTO2EntityList(List<ProyectoDTO> dtos){
		List<ProyectoEntity> entities=new ArrayList<ProyectoEntity>();
		for(ProyectoDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}