/* ========================================================================
 * Copyright 2014 astroDevelopers
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 astroDevelopers

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410261249

*/

package co.edu.uniandes.csw.astroDevelopers.noticia.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.astroDevelopers.noticia.logic.dto.NoticiaDTO;
import co.edu.uniandes.csw.astroDevelopers.noticia.persistence.api.INoticiaPersistence;
import co.edu.uniandes.csw.astroDevelopers.noticia.persistence.entity.NoticiaEntity;
import co.edu.uniandes.csw.astroDevelopers.noticia.persistence.converter.NoticiaConverter;
import static co.edu.uniandes.csw.astroDevelopers.util._TestUtil.*;

@RunWith(Arquillian.class)
public class NoticiaPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(NoticiaPersistence.class.getPackage())
				.addPackage(NoticiaEntity.class.getPackage())
				.addPackage(INoticiaPersistence.class.getPackage())
                .addPackage(NoticiaDTO.class.getPackage())
                .addPackage(NoticiaConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private INoticiaPersistence noticiaPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from NoticiaEntity").executeUpdate();
	}

	private List<NoticiaEntity> data=new ArrayList<NoticiaEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			NoticiaEntity entity=new NoticiaEntity();
			entity.setName(generateRandom(String.class));
			entity.setImagen(generateRandom(String.class));
			entity.setTitulo(generateRandom(String.class));
			entity.setFecha(generateRandom(Date.class));
			entity.setDescripcion(generateRandom(String.class));
			entity.setTema(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createNoticiaTest(){
		NoticiaDTO dto=new NoticiaDTO();
		dto.setName(generateRandom(String.class));
		dto.setImagen(generateRandom(String.class));
		dto.setTitulo(generateRandom(String.class));
dto.setFecha(generateRandomDate());
		dto.setDescripcion(generateRandom(String.class));
		dto.setTema(generateRandom(String.class));
		
		NoticiaDTO result=noticiaPersistence.createNoticia(dto);
		
		Assert.assertNotNull(result);
		
		NoticiaEntity entity=em.find(NoticiaEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getImagen(), entity.getImagen());
		Assert.assertEquals(dto.getTitulo(), entity.getTitulo());
Assert.assertEquals(parseDate(dto.getFecha()), entity.getFecha());	
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getTema(), entity.getTema());
	}
	
	@Test
	public void getNoticiasTest(){
		List<NoticiaDTO> list=noticiaPersistence.getNoticias();
		Assert.assertEquals(list.size(), data.size());
        for(NoticiaDTO dto:list){
        	boolean found=false;
            for(NoticiaEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getNoticiaTest(){
		NoticiaEntity entity=data.get(0);
		NoticiaDTO dto=noticiaPersistence.getNoticia(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getImagen(), dto.getImagen());
		Assert.assertEquals(entity.getTitulo(), dto.getTitulo());
		Assert.assertEquals(entity.getDescripcion(), dto.getDescripcion());
		Assert.assertEquals(entity.getTema(), dto.getTema());
        
	}
	
	@Test
	public void deleteNoticiaTest(){
		NoticiaEntity entity=data.get(0);
		noticiaPersistence.deleteNoticia(entity.getId());
        NoticiaEntity deleted=em.find(NoticiaEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateNoticiaTest(){
		NoticiaEntity entity=data.get(0);
		
		NoticiaDTO dto=new NoticiaDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setImagen(generateRandom(String.class));
		dto.setTitulo(generateRandom(String.class));
dto.setFecha(generateRandomDate());
		dto.setDescripcion(generateRandom(String.class));
		dto.setTema(generateRandom(String.class));
		
		
		noticiaPersistence.updateNoticia(dto);
		
		
		NoticiaEntity resp=em.find(NoticiaEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getImagen(), resp.getImagen());	
		Assert.assertEquals(dto.getTitulo(), resp.getTitulo());	
Assert.assertEquals(parseDate(dto.getFecha()), resp.getFecha());
		Assert.assertEquals(dto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(dto.getTema(), resp.getTema());	
	}
	
	
	
}